# MarketPrism 统一 NATS（JetStream） - 标准启动配置（简化稳定版）
# 端口：4222（客户端）、8222（监控）



services:
  nats:
    image: nats:2.10-alpine
    container_name: marketprism-nats
    hostname: nats
    restart: unless-stopped
    command: ["-js", "-m", "8222", "-sd", "/data/jetstream", "-n", "marketprism-nats"]
    ports:
      - "${NATS_PORT:-4222}:4222"
      - "${NATS_HTTP_PORT:-8222}:8222"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - nats_data:/data/jetstream
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  js-init:
    build:
      context: ../..
      dockerfile: services/message-broker/Dockerfile
    container_name: marketprism-js-init
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - MARKETPRISM_NATS_URL=nats://nats:4222
    volumes:
      - ../../scripts:/app/scripts:ro
    command: ["python", "services/message-broker/init_jetstream.py", "--wait", "--config", "scripts/js_init_market_data.yaml"]
    restart: "no"

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

volumes:
  nats_data:
