# MarketPrism 企业级可靠性系统配置
# 
# 此配置文件定义了熔断器、限流器、重试处理器和负载均衡器的参数
# 可根据实际业务需求调整各项参数

# 可靠性管理器全局配置
reliability_manager:
  name: "marketprism_reliability"
  
  # 组件启用开关
  components:
    circuit_breaker: true
    rate_limiter: true
    retry_handler: true
    load_balancer: true
  
  # 监控配置
  monitoring:
    metrics_collection_interval: 60.0    # 指标收集间隔(秒)
    enable_detailed_metrics: true        # 启用详细指标
    
  # 告警配置
  alerts:
    enabled: true
    thresholds:
      failure_rate: 0.1                  # 10%失败率告警
      response_time: 2.0                 # 2秒响应时间告警
      circuit_breaker_trips: 5           # 5次熔断告警
      rate_limit_rejections: 100         # 100次限流拒绝告警

# 熔断器配置
circuit_breaker:
  # 基础配置
  failure_threshold: 5                   # 失败阈值
  recovery_timeout: 30.0                 # 恢复超时时间(秒)
  half_open_max_calls: 3                 # 半开状态最大调用次数
  success_threshold: 2                   # 半开状态成功阈值
  timeout: 10.0                          # 操作超时时间(秒)
  
  # 高级配置
  failure_rate_threshold: 0.5            # 失败率阈值 (50%)
  minimum_throughput: 10                 # 最小吞吐量要求
  sliding_window_size: 100               # 滑动窗口大小
  slow_call_duration_threshold: 5.0      # 慢调用阈值(秒)

# 限流器配置
rate_limiter:
  # 基础配置
  max_requests_per_second: 100.0         # 每秒最大请求数
  burst_capacity: 200                    # 突发容量
  window_size_seconds: 60                # 窗口大小(秒)
  strategy: "adaptive"                   # 限流策略: token_bucket, sliding_window, adaptive
  
  # 自适应配置
  adaptive:
    factor: 1.0                          # 自适应因子
    min_rate_factor: 0.1                 # 最小速率因子
    max_rate_factor: 2.0                 # 最大速率因子
    adjustment_interval: 30.0            # 调整间隔(秒)
  
  # 优先级队列配置
  priority_queue:
    enabled: true                        # 启用优先级队列
    timeout: 30.0                        # 队列超时时间(秒)
    max_size: 1000                       # 最大队列大小

# 重试处理器配置
retry_handler:
  # 基础配置
  max_attempts: 3                        # 最大重试次数
  base_delay: 1.0                        # 基础延迟(秒)
  max_delay: 60.0                        # 最大延迟(秒)
  multiplier: 2.0                        # 延迟倍数
  jitter: true                           # 是否添加抖动
  jitter_range: 0.1                      # 抖动范围
  strategy: "exponential_backoff"        # 重试策略
  
  # 错误分类配置
  retryable_errors:
    - "ConnectionError"
    - "TimeoutError"
    - "RetryableException"
  
  non_retryable_errors:
    - "ValueError"
    - "TypeError"
    - "NonRetryableException"
  
  # 自适应配置
  adaptive:
    success_threshold: 0.8               # 成功率阈值
    failure_threshold: 0.5               # 失败率阈值
    adaptation_window: 100               # 自适应窗口大小

# 负载均衡器配置
load_balancer:
  # 基础配置
  strategy: "weighted_round_robin"       # 负载均衡策略
  health_check_interval: 30.0            # 健康检查间隔(秒)
  health_check_timeout: 5.0              # 健康检查超时(秒)
  max_failures: 3                        # 最大失败次数
  recovery_time: 60.0                    # 恢复时间(秒)
  
  # 自适应配置
  adaptive:
    enabled: true                        # 启用自适应
    interval: 60.0                       # 自适应间隔(秒)
    performance_window: 100              # 性能窗口大小
  
  # 连接管理
  connection:
    timeout: 30.0                        # 连接超时(秒)
    max_retries: 3                       # 最大重试次数

# 服务实例配置
instances:
  # 示例实例配置
  - id: "marketprism_collector_1"
    host: "192.168.1.10"
    port: 8080
    weight: 1.0
    max_connections: 100
    
  - id: "marketprism_collector_2"
    host: "192.168.1.11"
    port: 8080
    weight: 1.5
    max_connections: 150
    
  - id: "marketprism_collector_3"
    host: "192.168.1.12"
    port: 8080
    weight: 0.8
    max_connections: 80

# 环境特定配置
environments:
  development:
    circuit_breaker:
      failure_threshold: 3
      recovery_timeout: 10.0
    rate_limiter:
      max_requests_per_second: 50.0
    retry_handler:
      max_attempts: 2
      
  staging:
    circuit_breaker:
      failure_threshold: 4
      recovery_timeout: 20.0
    rate_limiter:
      max_requests_per_second: 75.0
    retry_handler:
      max_attempts: 3
      
  production:
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 30.0
    rate_limiter:
      max_requests_per_second: 100.0
    retry_handler:
      max_attempts: 3

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "console"
    - type: "file"
      filename: "logs/reliability.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5

# Prometheus监控配置
prometheus:
  enabled: true
  port: 9090
  metrics_path: "/metrics"
  
  # 自定义指标
  custom_metrics:
    - name: "reliability_requests_total"
      type: "counter"
      description: "Total number of requests processed"
      labels: ["component", "status"]
      
    - name: "reliability_response_time_seconds"
      type: "histogram"
      description: "Response time distribution"
      labels: ["component"]
      buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
      
    - name: "reliability_health_score"
      type: "gauge"
      description: "System health score"
      labels: ["component"] 