storage:
  backup:
    enabled: true
    path: ./data/backup
  clickhouse:
    database: marketprism
    host: localhost
    password: ''
    port: 8123
    timeout: 30
    user: default
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10
