
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: marketprism-prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle"]
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    depends_on: []
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: marketprism-alertmanager
    volumes:
      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]
    ports:
      - "9093:9093"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: marketprism-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_LOG_LEVEL=debug
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    container_name: marketprism-blackbox
    command: ["--config.file=/etc/blackbox_exporter/blackbox.yml"]
    volumes:
      - ./config/blackbox/blackbox.yml:/etc/blackbox_exporter/blackbox.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"


  dingtalk:
    build:
      context: ./dingtalk-webhook
    container_name: marketprism-dingtalk
    profiles:
      - dingtalk

    environment:
      - DINGTALK_WEBHOOK_URL=${DINGTALK_WEBHOOK_URL}
      - DINGTALK_SECRET=${DINGTALK_SECRET}
    volumes:
      - ./config/dingtalk/config.tmpl.yml:/etc/prometheus-webhook-dingtalk/config.tmpl.yml:ro
      - ./config/dingtalk/templates:/etc/prometheus-webhook-dingtalk/templates:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"


  nats-exporter:
    image: natsio/prometheus-nats-exporter:0.15.0
    container_name: marketprism-nats-exporter
    command: ["-varz", "-connz", "-subz", "-jsz", "streams", "http://host.docker.internal:8222"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

networks:
  default:
    name: marketprism-monitoring

volumes:
  grafana-data:

