version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: marketprism-nats
    ports:
      - "4222:4222"     # NATS客户端端口
      - "8222:8222"     # HTTP监控端口
      - "6222:6222"     # 路由端口
    command: [
      "--jetstream",     # 启用JetStream
      "--store_dir=/data", # 数据存储目录
      "--http_port=8222"   # HTTP监控端口
    ]
    volumes:
      - nats_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nats_data:
    driver: local

networks:
  default:
    name: marketprism