# Binance现货交易所配置 - Phase 4增量深度数据流

# 基础信息
exchange: binance
market_type: spot
enabled: true

# API配置
base_url: "https://api.binance.com"
ws_url: "wss://stream.binance.com:9443/ws"

# 数据类型
data_types:
  - "trade"
  - "orderbook"
  - "ticker"

# 交易对
symbols:
  - "BTCUSDT"
  - "ETHUSDT"

# 限制配置
max_requests_per_minute: 1200

# WebSocket配置
ping_interval: 30
reconnect_attempts: 5
reconnect_delay: 5

# 订单簿配置
snapshot_interval: 300  # 5分钟刷新一次快照，大幅减少API调用
depth_limit: 100  # 使用100档深度，最低API权重