# Binance 现货交易所配置
# 生成时间: 2025-05-24T13:50:00.000000
# 代理配置: 参考 config/collector/python-collector/collector.yaml 中的 proxy 配置
# 支持公共API接口（无需密钥）：获取服务器时间、交易所信息、订单薄快照等

exchange: "binance"
market_type: "spot"
enabled: false  # 临时禁用以专注于OKX测试

# API配置
base_url: "https://api.binance.com"
ws_url: "wss://stream.binance.com:9443/ws"
api_key: ""  # 从环境变量 BINANCE_SPOT_API_KEY 读取
api_secret: ""  # 从环境变量 BINANCE_SPOT_API_SECRET 读取

# 数据类型
data_types:
  - "trade"
  - "orderbook"
  - "ticker"

# 监听的交易对
symbols:
  - "BTC-USDT"
  - "ETH-USDT"

# 速率限制
max_requests_per_minute: 1200

# WebSocket配置
ping_interval: 30
reconnect_attempts: 5
reconnect_delay: 5

# 订单簿配置
snapshot_interval: 10
depth_limit: 20
