# Deribit交易所API配置
# 代理配置: 参考 config/collector/python-collector/collector.yaml 中的 proxy 配置
# 支持公共API接口（无需密钥）：获取服务器时间、订单薄快照等
exchange: deribit
market_type: all  # 合约和期权
enabled: true

# API认证信息
api:
  base_url: "https://www.deribit.com"
  ws_url: "wss://www.deribit.com/ws/api/v2"
  api_key: "YOUR_DERIBIT_API_KEY"       # 替换为你的Deribit API Key
  api_secret: "YOUR_DERIBIT_SECRET_KEY" # 替换为你的Deribit Secret Key

# 数据收集配置
data_types:
  - trade        # 交易数据
  - depth        # 订单簿深度数据
  - kline        # K线数据
  - markPrice    # 标记价格
  - funding      # 资金费率
  - openInterest # 持仓量
  - volatility   # 波动率
  - greeks       # 期权希腊字母

# 交易对配置
symbols:
  # 永续合约
  - BTC-PERPETUAL
  - ETH-PERPETUAL
  # 交割合约示例
  - BTC-30JUN23
  - ETH-30JUN23
  # 期权示例 (格式: 币种-到期日-行权价格-C/P)
  - BTC-30JUN23-30000-C
  - BTC-30JUN23-30000-P

# 请求频率限制
rate_limit:
  max_requests_per_minute: 100
  
# 其他配置
websocket:
  ping_interval: 30  # 秒
  reconnect_attempts: 5
  reconnect_delay: 5 # 秒
  
orderbook:
  snapshot_interval: 60 # 秒
  depth_limit: 100      # Deribit订单簿深度设置 