# Deribit 衍生品交易所配置
# 生成时间: 2025-05-24T13:50:00.000000

exchange: "deribit"
market_type: "derivatives"
enabled: false  # 临时禁用以专注于OKX测试

# API配置
base_url: "https://www.deribit.com"
ws_url: "wss://www.deribit.com/ws/api/v2"
api_key: ""  # 从环境变量 DERIBIT_API_KEY 读取
api_secret: ""  # 从环境变量 DERIBIT_API_SECRET 读取

# 数据类型
data_types:
  - "trade"
  - "orderbook"
  - "funding_rate"
  - "open_interest"

# 监听的交易对
symbols:
  - "BTC-PERPETUAL"
  - "ETH-PERPETUAL"
  - "BTC-25DEC25"
  - "ETH-25DEC25"

# 速率限制
max_requests_per_minute: 300

# WebSocket配置
ping_interval: 30
reconnect_attempts: 5
reconnect_delay: 5

# 订单簿配置
snapshot_interval: 10
depth_limit: 20 