# MarketPrism 交易所配置
# 统一管理所有支持的交易所连接和API配置

exchanges:
  binance:
    name: "Binance"
    enabled: true
    
    # API配置
    api:
      base_url: "https://api.binance.com"
      futures_base_url: "https://fapi.binance.com"
      websocket_url: "wss://stream.binance.com:9443/ws"
      futures_websocket_url: "wss://fstream.binance.com/ws"
      
    # 支持的产品类型
    supported_products:
      - "spot"
      - "futures"
      - "margin"
      
    # 支持的数据类型
    supported_data_types:
      - "trade"
      - "orderbook"
      - "ticker"
      - "kline"
      - "liquidation"
      - "funding_rate"
      - "open_interest"
      - "top_trader_ratio"
      - "market_ratio"
      
    # 连接配置
    connection:
      timeout: 30
      max_retries: 3
      retry_delay: 1
      heartbeat_interval: 30
      
    # 限流配置
    rate_limits:
      rest_api:
        requests_per_minute: 1200
        weight_per_minute: 6000
      websocket:
        connections_per_ip: 5
        subscriptions_per_connection: 1024

  okx:
    name: "OKX"
    enabled: true
    
    # API配置
    api:
      base_url: "https://www.okx.com"
      websocket_url: "wss://ws.okx.com:8443/ws/v5/public"
      websocket_private_url: "wss://ws.okx.com:8443/ws/v5/private"
      
    # 支持的产品类型
    supported_products:
      - "spot"
      - "swap"
      - "futures"
      - "margin"
      
    # 支持的数据类型
    supported_data_types:
      - "trade"
      - "orderbook"
      - "ticker"
      - "kline"
      - "liquidation"
      - "funding_rate"
      - "open_interest"
      - "top_trader_ratio"
      - "market_ratio"
      
    # 连接配置
    connection:
      timeout: 30
      max_retries: 3
      retry_delay: 1
      heartbeat_interval: 30
      
    # 限流配置
    rate_limits:
      rest_api:
        requests_per_second: 20
        requests_per_minute: 600
      websocket:
        connections_per_ip: 5
        subscriptions_per_connection: 100

  deribit:
    name: "Deribit"
    enabled: false  # 暂时禁用
    
    # API配置
    api:
      base_url: "https://www.deribit.com/api/v2"
      websocket_url: "wss://www.deribit.com/ws/api/v2"
      
    # 支持的产品类型
    supported_products:
      - "futures"
      - "options"
      
    # 支持的数据类型
    supported_data_types:
      - "trade"
      - "orderbook"
      - "ticker"
      - "liquidation"
      
    # 连接配置
    connection:
      timeout: 30
      max_retries: 3
      retry_delay: 1
      heartbeat_interval: 30

# 全局配置
global_settings:
  # 默认连接配置
  default_connection:
    timeout: 30
    max_retries: 3
    retry_delay: 1
    heartbeat_interval: 30
    
  # 数据质量配置
  data_quality:
    max_latency_ms: 1000
    min_data_freshness_seconds: 5
    max_error_rate: 0.05
    
  # 监控配置
  monitoring:
    health_check_interval: 60
    metrics_collection_interval: 30
    alert_thresholds:
      connection_failure_rate: 0.1
      data_latency_ms: 2000
      error_rate: 0.05

# 交易对映射
symbol_mapping:
  # 标准化交易对格式
  standard_format: "{base}-{quote}"
  
  # 交易所特定格式
  exchange_formats:
    binance:
      spot: "{base}{quote}"
      futures: "{base}USDT"
    okx:
      spot: "{base}-{quote}"
      swap: "{base}-{quote}-SWAP"
      futures: "{base}-{quote}-{expiry}"

# 数据类型映射
data_type_mapping:
  # 统一数据类型到交易所特定类型的映射
  trade:
    binance: "trade"
    okx: "trades"
    
  orderbook:
    binance: "depth"
    okx: "books"
    
  ticker:
    binance: "ticker"
    okx: "tickers"
    
  liquidation:
    binance: "forceOrder"
    okx: "liquidation-orders"

# 版本信息
version:
  config_version: "1.0.0"
  created_date: "2024-12-19"
  last_modified: "2024-12-19"
  description: "MarketPrism交易所配置 - 统一管理所有交易所连接和API配置"
