# OKX交易所配置 - Phase 4增量深度数据流

# 基础信息
exchange: okx
market_type: spot
enabled: true

# API配置
base_url: "https://www.okx.com"
ws_url: "wss://ws.okx.com:8443/ws/v5/public"

# 数据类型
data_types:
  - "trade"
  - "orderbook"

# 交易对
symbols:
  - "BTC-USDT"
  - "ETH-USDT"

# 限制配置
max_requests_per_minute: 1200

# WebSocket配置
ping_interval: 30
reconnect_attempts: 5
reconnect_delay: 5

# 订单簿配置
snapshot_interval: 10
depth_limit: 5000