# OKX 现货交易所配置
# 生成时间: 2025-05-24T13:50:00.000000

exchange: "okx"
market_type: "spot"
enabled: true

# API配置
base_url: "https://www.okx.com"
ws_url: "wss://ws.okx.com:8443/ws/v5/public"
api_key: ""  # 从环境变量 OKX_SPOT_API_KEY 读取
api_secret: ""  # 从环境变量 OKX_SPOT_API_SECRET 读取
passphrase: ""  # 从环境变量 OKX_SPOT_PASSPHRASE 读取

# 数据类型
data_types:
  - "trade"
  - "orderbook"

# 监听的交易对
symbols:
  - "BTC-USDT"
  - "ETH-USDT"
  - "ADA-USDT"

# 速率限制
max_requests_per_minute: 600

# WebSocket配置
ping_interval: 30
reconnect_attempts: 5
reconnect_delay: 5

# 订单簿配置
snapshot_interval: 10
depth_limit: 20 