# OKX WebSocket 交易所特定配置
# 基于官方文档: https://www.okx.com/docs-v5/zh/#overview-websocket

exchange_name: "okx"
version: "1.0.0"
last_updated: "2025-01-02"

# WebSocket连接配置
websocket:
  # 连接管理
  connection:
    # 基础URL配置
    base_urls:
      public: "wss://ws.okx.com:8443/ws/v5/public"
      private: "wss://ws.okx.com:8443/ws/v5/private"
      business: "wss://ws.okx.com:8443/ws/v5/business"
    
    # 连接限制（基于官方文档）
    limits:
      max_connections_per_second: 3         # 每秒最多3次连接请求（基于IP）
      max_requests_per_hour: 480            # 每连接每小时480次请求（订阅/取消订阅/登录）
      idle_timeout_seconds: 30              # 30秒无数据推送自动断开
      max_subscriptions_per_connection: 100 # 每连接最大订阅数（估算）
    
    # 连接参数
    parameters:
      auto_reconnect: true                  # 自动重连
      reconnect_delay_seconds: 3            # 重连延迟
      max_reconnect_attempts: 10            # 最大重连次数
      connection_timeout_seconds: 10        # 连接超时
  
  # 心跳机制（基于官方文档）
  heartbeat:
    # OKX心跳策略
    client_ping_interval_seconds: 25        # 客户端每25秒发送ping（小于30秒）
    server_pong_timeout_seconds: 30         # 服务器30秒内应回复pong
    
    # 客户端心跳配置
    client_strategy:
      enable_proactive_ping: true           # OKX需要客户端主动发送ping
      ping_message: "ping"                  # ping消息内容
      expected_pong_message: "pong"         # 期望的pong回复
      ping_payload_empty: true              # ping消息payload为空
    
    # 监控和告警
    monitoring:
      ping_timeout_warning_seconds: 35      # ping超时警告阈值
      connection_health_check_interval: 20  # 连接健康检查间隔
      consecutive_ping_failures_threshold: 3 # 连续ping失败阈值

# 订单簿维护配置
orderbook:
  # 维护方法
  maintenance_method: "okx_standard"
  
  # OKX标准方法配置
  standard_method:
    # 数据获取
    data_acquisition:
      rest_endpoint: "/api/v5/market/books-full"
      websocket_channel: "books"
      default_depth: 400                    # 默认深度档位
      max_depth: 400                        # 最大深度档位
    
    # 更新处理
    update_processing:
      enable_incremental_updates: true      # 启用增量更新
      update_id_field: "ts"                 # 更新时间戳字段
      sequence_validation: false            # OKX不强制序列号验证
      zero_quantity_removal: true           # 数量为0时移除价位
      absolute_quantity_mode: true          # 绝对数量模式
    
    # 同步策略
    sync_strategy:
      initial_sync_required: true           # 需要初始同步
      periodic_resync_interval_minutes: 60  # 定期重新同步间隔
      auto_resync_on_error: true            # 错误时自动重新同步
      resync_retry_attempts: 3              # 重新同步重试次数

# 数据流配置
streams:
  # 支持的频道类型
  supported_channels:
    - "tickers"       # 行情频道
    - "books"         # 深度频道
    - "books5"        # 5档深度
    - "books50-l2-tbt" # 50档逐笔深度（VIP4+）
    - "books-l2-tbt"  # 完整逐笔深度
    - "trades"        # 交易频道
    - "candle1m"      # 1分钟K线
    - "candle5m"      # 5分钟K线
    - "mark-price"    # 标记价格
  
  # VIP等级要求
  vip_requirements:
    "books50-l2-tbt": "VIP4"               # 50档逐笔深度需要VIP4+
    "books-l2-tbt": "VIP5"                 # 完整逐笔深度需要VIP5+
  
  # 订阅格式
  subscription_format:
    method: "subscribe"
    args_format: "array_of_objects"
    channel_field: "channel"
    symbol_field: "instId"
    symbol_case: "uppercase"                # 交易对名称大写

# 认证配置（私有频道）
authentication:
  # 登录参数
  login:
    required_for_private: true              # 私有频道需要登录
    method: "login"
    
  # 签名配置
  signature:
    algorithm: "HMAC_SHA256"
    encoding: "base64"
    timestamp_format: "unix_seconds"
    method_field: "GET"
    request_path: "/users/self/verify"
  
  # API密钥配置
  api_keys:
    api_key_field: "apiKey"
    passphrase_field: "passphrase"
    timestamp_field: "timestamp"
    signature_field: "sign"

# 错误处理和重试
error_handling:
  # 连接错误
  connection_errors:
    max_retry_attempts: 5
    retry_backoff_seconds: [2, 4, 8, 16, 32]
    fatal_error_codes: ["60009", "60011"]  # 登录失败等不重试的错误
  
  # 订阅错误
  subscription_errors:
    invalid_channel_action: "log_and_skip"
    rate_limit_action: "backoff_and_retry"
    auth_failure_action: "reauth_and_retry"
  
  # 数据错误
  data_errors:
    invalid_json_action: "log_and_continue"
    missing_fields_action: "log_and_continue"
    timestamp_drift_action: "log_and_continue"

# 性能优化
performance:
  # 缓冲区配置
  buffers:
    websocket_receive_buffer_size: 65536    # WebSocket接收缓冲区
    message_processing_queue_size: 5000     # 消息处理队列大小
    subscription_batch_size: 10             # 订阅批处理大小
  
  # 并发配置
  concurrency:
    max_concurrent_connections: 5           # 最大并发连接数
    message_processing_workers: 3           # 消息处理工作线程数
    subscription_processing_workers: 2      # 订阅处理工作线程数
  
  # 优化策略
  optimization:
    enable_message_compression: false       # OKX不支持压缩
    enable_binary_protocol: false          # 使用JSON协议
    batch_subscriptions: true              # 批量订阅

# 监控和日志
monitoring:
  # 指标收集
  metrics:
    enable_connection_metrics: true
    enable_subscription_metrics: true
    enable_message_metrics: true
    enable_latency_metrics: true
    enable_auth_metrics: true
  
  # 日志配置
  logging:
    websocket_events: "INFO"
    subscription_events: "INFO"
    authentication_events: "INFO"
    error_events: "ERROR"
    performance_events: "DEBUG"
  
  # 告警阈值
  alerts:
    connection_failure_threshold: 3         # 连接失败告警阈值
    subscription_failure_threshold: 5       # 订阅失败告警阈值
    auth_failure_threshold: 2              # 认证失败告警阈值
    message_delay_threshold_ms: 2000        # 消息延迟告警阈值

# 兼容性配置
compatibility:
  # API版本兼容性
  api_versions:
    websocket_version: "v5"
    rest_api_version: "v5"
  
  # 向后兼容
  backward_compatibility:
    legacy_channel_mapping: true            # 支持旧频道映射
    legacy_format_support: true            # 支持旧格式
    migration_mode: false                   # 迁移模式（渐进式升级）
  
  # 特殊配置
  special_features:
    support_business_channels: true         # 支持业务频道
    support_multi_account: false           # 不支持多账户登录
    support_dynamic_subscriptions: true    # 支持动态订阅
