# MarketPrism 分层数据存储服务配置
# 支持热端实时存储和冷端归档存储

# NATS配置 - 用于热端服务订阅数据
nats:
  servers:
    - "nats://marketprism-nats:4222"  # Docker网络内的NATS服务
  max_reconnect_attempts: 10
  reconnect_time_wait: 2

# HTTP服务器配置
http_port: 8085  # Hot Storage 服务 HTTP 端口（健康检查 8085/health）

# 热端存储配置 - 远程服务器ClickHouse
hot_storage:
  clickhouse_host: "clickhouse-hot"  # Docker网络内的ClickHouse服务
  clickhouse_port: 9000
  clickhouse_http_port: 8123
  clickhouse_user: "default"
  clickhouse_password: ""
  clickhouse_database: "marketprism_hot"
  retention_days: 3  # 热端数据保留3天
  batch_size: 1000   # 批量写入大小
  flush_interval: 5  # 刷新间隔（秒）

  # 连接池配置
  connection_pool:
    size: 10
    max_retries: 3
    timeout: 30

  # 性能配置
  performance:
    enable_compression: true
    compression_method: "zstd"
    compression_level: 3
    max_insert_threads: 4
    insert_quorum: 1

  # 表配置
  tables:
    schema_file: "config/clickhouse_schema.sql"
    auto_create: true
    auto_optimize: true

# 冷端存储配置 - 本地NAS ClickHouse
cold_storage:
  http_port: 8086

  clickhouse_host: "clickhouse-hot"  # Docker网络内的ClickHouse服务
  clickhouse_port: 9000
  clickhouse_http_port: 8123
  clickhouse_user: "default"
  clickhouse_password: ""
  clickhouse_database: "marketprism_cold"
  retention_days: 365  # 冷端数据保留1年
  batch_size: 5000     # 批量写入大小（更大批次提高效率）
  flush_interval: 30   # 刷新间隔（秒）

  # 连接池配置
  connection_pool:
    size: 5
    max_retries: 5
    timeout: 60

  # 性能配置
  performance:
    enable_compression: true
    compression_method: "zstd"
    compression_level: 6  # 冷端使用更高压缩比
    max_insert_threads: 2
    insert_quorum: 1

  # 表配置
  tables:
    schema_file: "config/clickhouse_schema.sql"
    auto_create: true
    auto_optimize: true

# 数据订阅配置 - 热端服务使用
subscriptions:
  # 启用的数据类型
  orderbook_enabled: true
  trade_enabled: true
  funding_rate_enabled: true
  open_interest_enabled: true
  liquidation_enabled: true
  lsr_enabled: true
  volatility_index_enabled: true

# 数据同步配置 - 冷端服务使用
sync:
  interval_hours: 6      # 同步间隔（小时）
  batch_hours: 24        # 每次同步的数据时间范围（小时）
  buffer_minutes: 2      # 同步缓冲时间（分钟），测试环境下设置较小以便快速验证
  cleanup_enabled: true  # 是否启用热端数据清理
  cleanup_delay_hours: 48  # 同步后多久清理热端数据（小时）

  # 需要同步的数据类型
  data_types:
    - "orderbook"
    - "trade"
    - "funding_rate"
    - "open_interest"
    - "liquidation"
    - "lsr"
    - "volatility_index"

  # 需要同步的交易所
  exchanges:
    - "binance_spot"
    - "binance_derivatives"
    - "okx_spot"
    - "okx_derivatives"
    - "deribit_derivatives"

  # 每个交易所的交易对配置
  symbols:
    binance_spot:
      - "BTC-USDT"
      - "ETH-USDT"
      - "BNB-USDT"
    binance_derivatives:
      - "BTC-USDT"
      - "ETH-USDT"
      - "BNB-USDT"
    okx_spot:
      - "BTC-USDT"
      - "ETH-USDT"
      - "OKB-USDT"
    okx_derivatives:
      - "BTC-USDT"
      - "ETH-USDT"
      - "OKB-USDT"
    deribit_derivatives:
      - "BTC-USD"
      - "ETH-USD"

# 日志配置
logging:
  level: "INFO"
  format: "json"
  output: "stdout"

# 监控配置
monitoring:
  health_check_interval: 30  # 健康检查间隔（秒）
  metrics_collection_interval: 60  # 指标收集间隔（秒）

# 性能配置
performance:
  max_concurrent_transfers: 5  # 最大并发传输任务数
  transfer_timeout_minutes: 60  # 传输任务超时时间（分钟）
  connection_pool_size: 10     # 连接池大小

# 安全配置
security:
  enable_ssl: false  # 是否启用SSL连接
  verify_checksums: true  # 是否验证数据校验和
  encrypt_transfers: false  # 是否加密数据传输
