# MarketPrism订单簿管理系统告警规则

groups:
  - name: marketprism_orderbook_alerts
    rules:
      # 服务可用性告警
      - alert: OrderBookManagerDown
        expr: up{job="marketprism-orderbook"} == 0
        for: 30s
        labels:
          severity: critical
          service: orderbook-manager
        annotations:
          summary: "订单簿管理系统服务不可用"
          description: "订单簿管理系统已停止响应超过30秒"

      # 高错误率告警
      - alert: HighErrorRate
        expr: rate(marketprism_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: orderbook-manager
        annotations:
          summary: "订单簿管理系统错误率过高"
          description: "错误率: {{ $value | humanizePercentage }}"

      # 高延迟告警
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(marketprism_request_duration_seconds_bucket[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          service: orderbook-manager
        annotations:
          summary: "订单簿管理系统延迟过高"
          description: "95%分位延迟: {{ $value }}秒"

      # 内存使用告警
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes{job="marketprism-orderbook"} / 1024 / 1024 / 1024) > 1.5
        for: 5m
        labels:
          severity: warning
          service: orderbook-manager
        annotations:
          summary: "订单簿管理系统内存使用过高"
          description: "内存使用: {{ $value | humanize }}GB"

      # WebSocket连接告警
      - alert: WebSocketDisconnected
        expr: marketprism_websocket_connected == 0
        for: 1m
        labels:
          severity: critical
          service: orderbook-manager
        annotations:
          summary: "WebSocket连接断开"
          description: "交易所WebSocket连接已断开"

      # 订单簿更新延迟告警
      - alert: OrderBookUpdateDelay
        expr: time() - marketprism_last_orderbook_update_timestamp > 30
        for: 1m
        labels:
          severity: warning
          service: orderbook-manager
        annotations:
          summary: "订单簿更新延迟"
          description: "订单簿超过30秒未更新"

      # NATS消息发布失败告警
      - alert: NATSPublishFailure
        expr: rate(marketprism_nats_publish_errors_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          service: orderbook-manager
        annotations:
          summary: "NATS消息发布失败率过高"
          description: "NATS发布失败率: {{ $value | humanizePercentage }}"

  - name: infrastructure_alerts
    rules:
      # NATS服务告警
      - alert: NATSDown
        expr: up{job="nats"} == 0
        for: 30s
        labels:
          severity: critical
          service: nats
        annotations:
          summary: "NATS服务不可用"
          description: "NATS消息队列服务已停止"

      # ClickHouse服务告警
      - alert: ClickHouseDown
        expr: up{job="clickhouse"} == 0
        for: 30s
        labels:
          severity: critical
          service: clickhouse
        annotations:
          summary: "ClickHouse服务不可用"
          description: "ClickHouse数据库服务已停止"

      # Redis服务告警
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis服务不可用"
          description: "Redis缓存服务已停止"

      # 磁盘空间告警
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "磁盘空间不足"
          description: "可用磁盘空间低于10%"

      # CPU使用率告警
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "CPU使用率过高"
          description: "CPU使用率: {{ $value | humanizePercentage }}"

  - name: business_alerts
    rules:
      # 交易对数量告警
      - alert: LowSymbolCount
        expr: marketprism_active_symbols_count < 5
        for: 5m
        labels:
          severity: warning
          service: orderbook-manager
        annotations:
          summary: "活跃交易对数量过低"
          description: "当前活跃交易对数量: {{ $value }}"

      # 数据质量告警
      - alert: DataQualityIssue
        expr: rate(marketprism_data_validation_errors_total[5m]) > 0.01
        for: 2m
        labels:
          severity: warning
          service: orderbook-manager
        annotations:
          summary: "数据质量问题"
          description: "数据验证错误率: {{ $value | humanizePercentage }}"

      # 同步状态告警
      - alert: OrderBookOutOfSync
        expr: marketprism_orderbook_sync_status == 0
        for: 2m
        labels:
          severity: critical
          service: orderbook-manager
        annotations:
          summary: "订单簿同步失败"
          description: "订单簿与交易所失去同步"
