# 永续合约数据源配置
# 专门用于永续合约（SWAP）数据收集

# 数据收集配置
data_collection:
  # 数据类型配置
  data_types:
    - orderbook    # 订单簿数据
    - trade        # 交易数据
    - funding_rate # 资金费率（永续合约特有）
    - open_interest # 持仓量（永续合约特有）
    - liquidation  # 强平数据（永续合约特有）

  # 订单簿配置
  orderbook:
    depth_limit: 1000        # 订单簿深度限制
    snapshot_interval: 60    # 快照同步间隔（秒）
    update_frequency: 100    # 更新频率（毫秒）
    validation_enabled: true # 启用订单簿验证

  # 交易数据配置
  trade:
    buffer_size: 1000       # 交易数据缓冲区大小
    batch_size: 100         # 批量处理大小

  # 永续合约特有配置
  perpetual:
    funding_rate_interval: 300  # 资金费率更新间隔（秒）
    open_interest_interval: 10  # 持仓量更新间隔（秒）
    liquidation_realtime: true # 实时强平数据

# 交易所配置
exchanges:
  # Binance永续合约配置
  binance:
    name: "binance"
    market_type: "swap"
    enabled: true
    
    # API配置
    api:
      base_url: "https://fapi.binance.com"  # 永续合约API端点
      ws_url: "wss://fstream.binance.com/ws"  # 永续合约WebSocket端点
      rate_limit:
        requests_per_minute: 1200
        weight_per_minute: 6000
    
    # 永续合约交易对
    symbols:
      swap: ["BTCUSDT", "ETHUSDT"]  # BTC和ETH永续合约
    
    # 数据类型
    data_types: ["orderbook", "trade", "funding_rate", "open_interest", "liquidation"]
    
    # 连接配置
    connection:
      timeout: 30
      max_retries: 3
      retry_delay: 5
      heartbeat_interval: 20  # Binance服务器主动ping

  # OKX永续合约配置
  okx:
    name: "okx"
    market_type: "swap"
    enabled: true
    
    # API配置
    api:
      base_url: "https://www.okx.com"
      ws_url: "wss://ws.okx.com:8443/ws/v5/public"
      rate_limit:
        connections_per_hour: 480  # OKX连接限制
        subscriptions_per_connection: 240
    
    # 永续合约交易对（OKX格式）
    symbols:
      swap: ["BTC-USDT-SWAP", "ETH-USDT-SWAP"]  # BTC和ETH永续合约
    
    # 数据类型
    data_types: ["orderbook", "trade", "funding_rate", "open_interest", "liquidation"]
    
    # 连接配置
    connection:
      timeout: 30
      max_retries: 3
      retry_delay: 5
      heartbeat_interval: 25  # OKX客户端主动ping

# NATS配置
nats:
  # 永续合约数据流命名规范
  streams:
    orderbook: "orderbook-data.{exchange}.swap.{symbol}"
    trade: "trade-data.{exchange}.swap.{symbol}"
    funding_rate: "funding-rate.{exchange}.swap.{symbol}"
    open_interest: "open-interest.{exchange}.swap.{symbol}"
    liquidation: "liquidation-orders.{exchange}.swap.{symbol}"
  
  # 连接配置
  connection:
    servers: ["nats://localhost:4222"]
    max_reconnect_attempts: 10
    reconnect_time_wait: 2

# ClickHouse配置
clickhouse:
  # 永续合约数据表
  tables:
    orderbook: "marketprism.orderbook_swap"
    trade: "marketprism.trades_swap"
    funding_rate: "marketprism.funding_rates"
    open_interest: "marketprism.open_interest"
    liquidation: "marketprism.liquidations_swap"
  
  # 分区策略
  partitioning:
    by_exchange: true
    by_date: true
    retention_days: 30

# 日志配置
logging:
  level: "INFO"
  format: "json"
  file: "/tmp/swap-data-collector.log"
  max_size: "100MB"
  backup_count: 5

# 监控配置
monitoring:
  metrics_enabled: true
  health_check_interval: 30
  performance_tracking: true
  
  # 永续合约特有监控指标
  swap_metrics:
    funding_rate_updates: true
    open_interest_changes: true
    liquidation_events: true
    basis_tracking: true  # 现货-期货价差跟踪

# 错误处理配置
error_handling:
  max_consecutive_errors: 5
  backoff_multiplier: 2.0
  max_backoff_seconds: 300
  
  # 永续合约特有错误处理
  swap_errors:
    funding_rate_timeout: 600  # 资金费率超时（秒）
    position_data_timeout: 120 # 持仓数据超时（秒）
    liquidation_delay_threshold: 5  # 强平数据延迟阈值（秒）
