version: '3.8'

# 开发环境快速启动配置
services:
  # 开发模式 - 使用卷挂载，避免重复构建
  nats:
    image: nats:2.9.15-alpine
    ports: ["4222:4222", "8222:8222"]
    command: ["--jetstream", "--http_port=8222"]
    
  clickhouse:
    image: clickhouse/clickhouse-server:22.3
    ports: ["8123:8123", "9000:9000"]
    environment:
      - CLICKHOUSE_DB=marketprism
    volumes:
      - clickhouse_dev:/var/lib/clickhouse

  # 开发模式Python收集器 - 直接挂载代码
  python-collector:
    image: python:3.9-alpine
    volumes:
      - ./services/python-collector:/app
      - pip_cache:/root/.cache/pip
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
      - MP_CONFIG_PATH=/app/config/collector.yaml
    command: sh -c "pip install -r requirements.txt && python -m src.marketprism_collector.main"
    ports: ["8080:8080"]
    depends_on: [nats, clickhouse]

volumes:
  clickhouse_dev:
  pip_cache:
