# RabbitMQ告警规则配置

groups:
  - name: rabbitmq.rules
    rules:
      # RabbitMQ服务可用性
      - alert: RabbitMQDown
        expr: up{job="rabbitmq"} == 0
        for: 1m
        labels:
          severity: critical
          priority: p1
          service: rabbitmq
        annotations:
          summary: "RabbitMQ服务不可用"
          description: "RabbitMQ服务已停止响应超过1分钟"

      # 队列消息堆积
      - alert: RabbitMQQueueMessagesHigh
        expr: rabbitmq_queue_messages > 1000
        for: 5m
        labels:
          severity: warning
          priority: p2
          service: rabbitmq
        annotations:
          summary: "RabbitMQ队列消息堆积"
          description: "队列 {{ $labels.queue }} 中有 {{ $value }} 条未处理消息"

      # 队列消息堆积严重
      - alert: RabbitMQQueueMessagesCritical
        expr: rabbitmq_queue_messages > 5000
        for: 2m
        labels:
          severity: critical
          priority: p1
          service: rabbitmq
        annotations:
          summary: "RabbitMQ队列消息严重堆积"
          description: "队列 {{ $labels.queue }} 中有 {{ $value }} 条未处理消息，可能影响系统性能"

      # 内存使用率高
      - alert: RabbitMQMemoryHigh
        expr: (rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes) > 0.8
        for: 5m
        labels:
          severity: warning
          priority: p2
          service: rabbitmq
        annotations:
          summary: "RabbitMQ内存使用率过高"
          description: "RabbitMQ内存使用率为 {{ $value | humanizePercentage }}，超过80%阈值"

      # 内存使用率严重
      - alert: RabbitMQMemoryCritical
        expr: (rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes) > 0.9
        for: 2m
        labels:
          severity: critical
          priority: p1
          service: rabbitmq
        annotations:
          summary: "RabbitMQ内存使用率严重"
          description: "RabbitMQ内存使用率为 {{ $value | humanizePercentage }}，超过90%阈值，可能导致服务不稳定"

      # 磁盘空间不足
      - alert: RabbitMQDiskSpaceLow
        expr: rabbitmq_disk_space_available_bytes < 1073741824  # 1GB
        for: 5m
        labels:
          severity: warning
          priority: p2
          service: rabbitmq
        annotations:
          summary: "RabbitMQ磁盘空间不足"
          description: "RabbitMQ可用磁盘空间仅剩 {{ $value | humanizeBytes }}"

      # 连接数过多
      - alert: RabbitMQConnectionsHigh
        expr: rabbitmq_connections > 100
        for: 5m
        labels:
          severity: warning
          priority: p3
          service: rabbitmq
        annotations:
          summary: "RabbitMQ连接数过多"
          description: "当前RabbitMQ连接数为 {{ $value }}，可能影响性能"

      # 消息发布速率异常
      - alert: RabbitMQPublishRateHigh
        expr: rate(rabbitmq_channel_messages_published_total[5m]) > 1000
        for: 5m
        labels:
          severity: info
          priority: p4
          service: rabbitmq
        annotations:
          summary: "RabbitMQ消息发布速率过高"
          description: "消息发布速率为 {{ $value }} 消息/秒，请检查是否正常"

      # 消息消费速率异常低
      - alert: RabbitMQConsumeRateLow
        expr: rate(rabbitmq_queue_messages_delivered_total[5m]) < 10
        for: 10m
        labels:
          severity: warning
          priority: p3
          service: rabbitmq
        annotations:
          summary: "RabbitMQ消息消费速率过低"
          description: "消息消费速率为 {{ $value }} 消息/秒，可能存在消费者问题"

      # 队列无消费者
      - alert: RabbitMQQueueNoConsumers
        expr: rabbitmq_queue_consumers == 0 and rabbitmq_queue_messages > 0
        for: 5m
        labels:
          severity: warning
          priority: p2
          service: rabbitmq
        annotations:
          summary: "RabbitMQ队列无消费者"
          description: "队列 {{ $labels.queue }} 有消息但无消费者，消息可能无法被处理"

      # 节点分区
      - alert: RabbitMQNodePartition
        expr: rabbitmq_partitions > 0
        for: 1m
        labels:
          severity: critical
          priority: p1
          service: rabbitmq
        annotations:
          summary: "RabbitMQ集群节点分区"
          description: "检测到RabbitMQ集群节点分区，可能导致数据不一致"

      # 文件描述符使用率高
      - alert: RabbitMQFileDescriptorsHigh
        expr: (rabbitmq_process_open_fds / rabbitmq_process_max_fds) > 0.8
        for: 5m
        labels:
          severity: warning
          priority: p3
          service: rabbitmq
        annotations:
          summary: "RabbitMQ文件描述符使用率过高"
          description: "文件描述符使用率为 {{ $value | humanizePercentage }}，可能影响新连接建立"

      # Exchange无绑定
      - alert: RabbitMQExchangeNoBindings
        expr: rabbitmq_exchange_bindings == 0 and rabbitmq_exchange_messages_published_total > 0
        for: 10m
        labels:
          severity: info
          priority: p4
          service: rabbitmq
        annotations:
          summary: "RabbitMQ Exchange无绑定"
          description: "Exchange {{ $labels.exchange }} 有消息发布但无队列绑定，消息可能丢失"
