version: '3.8'

services:
  rabbitmq-monitoring:
    image: rabbitmq:3.12-management
    container_name: marketprism-rabbitmq
    hostname: rabbitmq-monitoring
    restart: unless-stopped
    
    # 端口配置 - 避免与NATS冲突
    ports:
      - "5672:5672"     # AMQP端口
      - "15672:15672"   # 管理界面端口
      - "25672:25672"   # 集群通信端口
    
    # 环境变量配置
    environment:
      RABBITMQ_DEFAULT_USER: marketprism
      RABBITMQ_DEFAULT_PASS: marketprism_monitor_2024
      RABBITMQ_DEFAULT_VHOST: /monitoring
      RABBITMQ_ERLANG_COOKIE: marketprism_rabbitmq_cookie
      
    # 数据卷挂载
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./logs:/var/log/rabbitmq
    
    # 网络配置
    networks:
      - marketprism-monitoring
    
    # 健康检查
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

networks:
  marketprism-monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
