# Cold Storage 独立模块配置（测试阶段默认：cleanup 禁用）
hot_storage:
  clickhouse_host: ${HOT_CH_HOST:-clickhouse-hot}
  clickhouse_tcp_port: ${HOT_CH_TCP_PORT:-9000}
  clickhouse_user: ${HOT_CH_USER:-default}
  clickhouse_password: ${HOT_CH_PWD:-}
  clickhouse_database: ${HOT_CH_DB:-marketprism_hot}

cold_storage:
  clickhouse_host: ${COLD_CH_HOST:-clickhouse-cold}   # 远端NAS上线时改为NAS域名/IP
  clickhouse_tcp_port: ${COLD_CH_TCP_PORT:-9001}
  clickhouse_user: ${COLD_CH_USER:-default}
  clickhouse_password: ${COLD_CH_PWD:-}
  clickhouse_database: ${COLD_CH_DB:-marketprism_cold}
  http_port: 8086

replication:
  enabled: true
  interval_seconds: 60
  window_minutes_all: 1
  safety_lag_minutes: 2
  cleanup_enabled: false
  cleanup_delay_minutes: 60

