# Cold Storage 独立模块配置（测试阶段默认：cleanup 禁用）
hot_storage:
  # 默认使用容器网络主机名；开发态通过 docker-compose 注入 HOT_CH_HOST=host.docker.internal 覆盖
  clickhouse_host: ${HOT_CH_HOST:-clickhouse-hot}
  clickhouse_tcp_port: ${HOT_CH_TCP_PORT:-9000}
  clickhouse_user: ${HOT_CH_USER:-default}
  clickhouse_password: ${HOT_CH_PWD:-}
  clickhouse_database: ${HOT_CH_DB:-marketprism_hot}

cold_storage:
  # 默认使用容器网络主机名；开发/测试与生产均通过环境变量覆盖（compose/部署系统注入）
  clickhouse_host: ${COLD_CH_HOST:-clickhouse-cold}
  clickhouse_tcp_port: ${COLD_CH_TCP_PORT:-9000}
  clickhouse_user: ${COLD_CH_USER:-default}
  clickhouse_password: ${COLD_CH_PWD:-}
  clickhouse_database: ${COLD_CH_DB:-marketprism_cold}
  http_port: 8086

replication:
  enabled: true
  # 一次性全历史回填开关（true=在首次启动时回填热端全部历史；仅执行一次）
  bootstrap_full_history: true
  # 复制循环节奏与窗口
  interval_seconds: 30
  window_minutes_all: 5
  safety_lag_minutes: 2
  # 每轮最大追赶窗口数（越大回填越快，但会更吃资源）
  max_catchup_windows_high: 60
  max_catchup_windows_low: 24
  # 清理策略（复制确认后删除热端数据）
  cleanup_enabled: true
  cleanup_delay_minutes: 30

