exchanges:
  binance:
    data_types:
    - ticker
    enabled: true
    market_type: spot
    ping_interval: 30
    reconnect_attempts: 10
    reconnect_delay: 5
    symbols:
    - BTCUSDT
    ws_url: wss://stream.binance.com:9443/ws
