exchanges:
  binance:
    data_types:
    - ticker
    enabled: true
    market_type: spot
    ping_interval: 10
    reconnect_attempts: 5
    reconnect_delay: 2
    symbols:
    - BTCUSDT
    ws_url: wss://stream.binance.com:9443/ws
nats:
  max_reconnect_attempts: 3
  servers:
  - nats://localhost:4222
