# MarketPrism数据收集器主配置文件

# 基础配置
collector:
  # 是否使用真实交易所数据(false则使用模拟数据)
  use_real_exchanges: true
  # 日志级别: debug, info, warn, error
  log_level: info
  # 健康检查HTTP服务端口
  http_port: 8081
  # Prometheus指标端口
  metrics_port: 8081
  # 最大重连次数
  max_reconnect_attempts: 10
  # 重连间隔(秒)
  reconnect_delay: 5

# NATS消息队列配置
nats:
  url: "nats://localhost:4222"
  client_name: "market-data-collector"
  # 消息流配置
  streams:
    # 币安交易流
    binance_trades:
      name: "BINANCE_TRADES"
      subjects: ["binance.trade.*"]
      retention: "limits"
      max_msgs: 10000
      max_bytes: 1073741824  # 1GB
      max_age: 3600000000000 # 1小时
    # 币安订单簿流
    binance_orderbook:
      name: "BINANCE_ORDERBOOK"
      subjects: ["binance.orderbook.*"]
      retention: "limits"
      max_msgs: 5000
      max_bytes: 1073741824  # 1GB
      max_age: 3600000000000 # 1小时
    # OKX交易流
    okx_trades:
      name: "OKX_TRADES"
      subjects: ["okx.trade.*"]
      retention: "limits"
      max_msgs: 10000
      max_bytes: 1073741824  # 1GB
      max_age: 3600000000000 # 1小时
    # Deribit交易流
    deribit_trades:
      name: "DERIBIT_TRADES"
      subjects: ["deribit.trade.*"]
      retention: "limits"
      max_msgs: 10000
      max_bytes: 1073741824  # 1GB
      max_age: 3600000000000 # 1小时

# 加载交易所配置文件
exchanges:
  # 配置文件列表(相对于config/exchanges目录)
  configs:
    - binance_spot.yaml
    - binance_futures.yaml
    - binance_coin_futures.yaml
    - okx.yaml
    - deribit.yaml

# 代理配置
proxy:
  enabled: true
  # REST API使用HTTP代理
  rest_api:
    http_proxy: "http://127.0.0.1:1087"
    https_proxy: "http://127.0.0.1:1087"
  # WebSocket使用SOCKS代理
  websocket:
    socks_proxy: "socks5://127.0.0.1:1080"
  # 不使用代理的地址
  no_proxy: "localhost,127.0.0.1"
  # 兼容性配置（向后兼容）
  http_proxy: "http://127.0.0.1:1087"
  https_proxy: "http://127.0.0.1:1087"

# 热数据存储配置
hot_storage:
  # 是否启用热数据存储
  enabled: true
  # 热数据TTL（秒）
  hot_data_ttl: 3600  # 1小时
  # 是否启用实时更新
  real_time_updates: true
  # 数据压缩
  compression: true
  # 缓存策略
  cache_strategy: "write_through"
  
  # ClickHouse热数据配置
  clickhouse:
    host: "localhost"
    port: 8123
    user: "default"
    password: ""
    database: "marketprism_hot"
    connection_pool_size: 10
    batch_size: 1000
    flush_interval: 5
    max_retries: 3
    
  # Redis热缓存配置
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    ttl: 3600
    connection_pool_size: 10

# 冷数据存储配置
cold_storage:
  # 是否启用冷数据存储
  enabled: true
  # 冷数据TTL（秒），30天
  cold_data_ttl: 2592000
  # 归档阈值（天），超过此天数的热数据将被归档到冷存储
  archive_threshold_days: 7
  
  # ClickHouse冷数据配置
  clickhouse:
    host: "localhost"
    port: 8123
    user: "default"
    password: ""
    database: "marketprism_cold"
    connection_pool_size: 5
    batch_size: 5000
    flush_interval: 60
    max_retries: 3
  
  # 分区配置
  partitioning:
    # 按月分区：toYYYYMM(timestamp)
    # 按天分区：toYYYYMMDD(timestamp)
    # 按周分区：toYearWeek(timestamp)
    partition_by: "toYYYYMM(timestamp)"
  
  # 压缩配置
  compression:
    enabled: true
    # 支持的压缩算法：LZ4, ZSTD, Delta, DoubleDelta
    codec: "LZ4"
  
  # 自动归档配置
  archiving:
    enabled: true
    batch_size: 10000
    # 归档任务执行间隔（小时）
    interval_hours: 24 