# MarketPrism Collector Configuration - Phase 4 增量深度数据流
# 专注于增量深度数据的双路处理架构

collector:
  name: "marketprism-collector-phase4"
  log_level: "INFO"
  http_port: 8080
  enable_orderbook_manager: true  # 启用OrderBook Manager
  enable_scheduler: false  # 暂时禁用调度器

# NATS配置
nats:
  servers: ["nats://localhost:4222"]
  streams:
    MARKET_DATA:
      subjects: ["market.data.>"]
      retention: "workqueue"
      max_age: 3600  # 1小时
      max_msgs: 1000000
      storage: "memory"

# 数据发布配置
publisher:
  type: "enhanced"  # 使用增强发布器
  batch_size: 100
  flush_interval: 1.0

# 交易所配置 - 暂时只使用Binance
exchanges:
  configs:
    - "exchanges/binance_spot_phase4.yaml"

# 监控配置
monitoring:
  enabled: true
  metrics_interval: 30
  health_check_interval: 10