# MarketPrism主配置文件 - 生产环境版本
# 版本信息
config_version: "1.2.0"
last_updated: "2025-05-08"

# 代理配置 - 生产环境禁用
proxy:
  enabled: false  # 生产环境中禁用代理

# NATS配置
nats:
  url: "nats://nats:4222"  # 基础连接（非SSL）
  # SSL配置（默认关闭，需要时取消注释并修改url为tls://）
  # url: "tls://nats:4222"  # SSL连接
  # ssl:
  #   enabled: true
  #   ca_file: "/app/ssl-certs/nats/ca-cert.pem"  # CA证书路径
  #   cert_file: "/app/ssl-certs/nats/cert.pem"  # 客户端证书路径
  #   key_file: "/app/ssl-certs/nats/key.pem"  # 客户端私钥路径
  #   verify: true  # 是否验证服务器证书
  reconnect:
    max_attempts: 10
    wait_time: 5  # 秒
  stream:
    max_msgs: 100000  # 每个流的最大消息数
    max_age: 3600     # 消息保留时间(秒)
    subjects:
      trades: "binance.trade.*"
      depth: "binance.depth.*"
      orderbook: "binance.orderbook.*"

# Redis配置（已弃用 - 保留空配置以兼容旧版本）
redis:
  host: ""  # 字符串必须为空
  port: 0   # 数值设为0表示未使用
  db: 0     # 数值设为0表示未使用

# ClickHouse配置
clickhouse:
  host: "clickhouse"  # 主机名或IP
  port: 9000  # 标准TCP端口
  database: "marketprism"
  user: "default"
  password: ""

# 数据采集配置 (已迁移到python-collector)
# 此配置保留用于向后兼容，新部署请使用services/python-collector/config/collector.yaml
legacy_ingestion:
  binance:
    # API版本管理
    api_version: "2025-03-10"  # 记录当前使用的API版本，便于更新检查
    use_testnet: false  # 是否使用测试网环境

    # 交易对和数据类型
    symbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT"]  # 要监控的交易对
    data_types: ["trade", "bookTicker", "depth"]  # 数据类型
    
    # WebSocket设置
    websocket:
      base_url: "wss://stream.binance.com:9443"  # 生产环境WebSocket URL
      reconnect_attempts: 10
      ping_interval: 20  # 秒，根据2025年更新的规范
      reconnect_delay: 5 # 秒，基础重连延迟

    # REST API设置
    rest:
      base_url: "https://api.binance.com"  # 生产环境REST API URL
      orderbook_snapshot_interval: 60  # 秒
      depth_limit: 500
      
      # 请求频率限制配置（根据最新文档）
      rate_limits:
        # 币安2025年3月5日更新 - aggTrade权重从2增加到4
        agg_trade_weight: 4
        # 其他接口的权重限制
        ip_limits:
          requests_per_minute: 1200  # IP每分钟请求数
          orders_per_second: 50      # IP每秒订单数
          orders_per_day: 160000     # IP每天订单数

# 监控配置
monitoring:
  prometheus:
    enabled: true
    port: 8000

# 日志配置
logging:
  level: "INFO"  # 日志级别: DEBUG, INFO, WARNING, ERROR
  format: json
  file: "/var/log/marketprism/app.log" 

# 数据处理配置
processing:
  batch_size: 1000  # 批处理大小
  flush_interval_ms: 1000  # 刷新间隔(毫秒) 