# MarketPrism 公开数据源配置
# 使用无需API密钥的公开端点收集市场数据

data_sources:
  # Binance 公开API配置
  binance:
    enabled: true
    name: "Binance"
    base_url: "https://api.binance.com"
    websocket_url: "wss://stream.binance.com:9443"
    
    # REST API端点
    endpoints:
      orderbook: "/api/v3/depth"
      recent_trades: "/api/v3/trades"
      klines: "/api/v3/klines"
      exchange_info: "/api/v3/exchangeInfo"
    
    # WebSocket流
    websocket_streams:
      # 单一交易对流
      trade: "{symbol}@trade"
      depth: "{symbol}@depth"
      kline: "{symbol}@kline_{interval}"
      
      # 全市场流
    
    # 支持的交易对
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "BNBUSDT"
      - "ADAUSDT"
      - "XRPUSDT"
      - "SOLUSDT"
      - "DOTUSDT"
      - "DOGEUSDT"
      - "AVAXUSDT"
      - "MATICUSDT"
    
    # 请求限制
    rate_limits:
      rest_requests_per_minute: 1200
      websocket_connections_max: 5
      
  # OKX 公开API配置
  okx:
    enabled: true
    name: "OKX"
    base_url: "https://www.okx.com"
    websocket_url: "wss://ws.okx.com:8443/ws/v5/public"
    
    # REST API端点
    endpoints:
      orderbook: "/api/v5/market/books"
      recent_trades: "/api/v5/market/trades"
      candles: "/api/v5/market/candles"
      instruments: "/api/v5/public/instruments"
    
    # WebSocket频道
    websocket_channels:
      trade: "trades"
      orderbook: "books"
      candlestick: "candle{interval}"
    
    # 支持的交易对
    symbols:
      - "BTC-USDT"
      - "ETH-USDT"
      - "BNB-USDT"
      - "ADA-USDT"
      - "XRP-USDT"
      - "SOL-USDT"
      - "DOT-USDT"
      - "DOGE-USDT"
      - "AVAX-USDT"
      - "MATIC-USDT"
    
    # 请求限制
    rate_limits:
      rest_requests_per_second: 20
      websocket_connections_max: 5

  # Coinbase配置已移除 - 简化交易所集成，仅保留Binance、OKX、Deribit

# 数据收集配置
collection:
  # 收集间隔
  intervals:
    orderbook_rest_seconds: 60   # REST API订单簿收集间隔
    websocket_reconnect_seconds: 30  # WebSocket重连间隔
    
  # 数据质量控制
  quality_control:
    max_price_change_percent: 50  # 最大价格变化百分比
    min_volume_threshold: 1000    # 最小交易量阈值
    data_freshness_seconds: 300   # 数据新鲜度阈值
    
  # 容错机制
  fault_tolerance:
    max_retries: 3
    retry_delay_seconds: 5
    circuit_breaker_threshold: 10
    circuit_breaker_timeout_seconds: 300
    
  # 数据存储
  storage:
    batch_size: 100
    flush_interval_seconds: 10
    enable_compression: true
    
# 监控配置
monitoring:
  # 指标收集
  metrics:
    enable_collection_metrics: true
    enable_latency_metrics: true
    enable_error_metrics: true
    
  # 健康检查
  health_checks:
    api_connectivity_timeout_seconds: 10
    websocket_ping_interval_seconds: 30
    data_freshness_check_interval_seconds: 60
