# MarketPrism 服务管理配置
# 用于自动重启、健康检查、故障恢复

services:
  message-broker:
    command: "python3 services/message-broker/main.py -c services/message-broker/config/unified_message_broker.yaml"
    working_dir: "/home/ubuntu/marketprism"
    env_vars:
      PYTHONPATH: "/home/ubuntu/marketprism"
      VIRTUAL_ENV: "/home/ubuntu/marketprism/services/message-broker/.venv"
      PATH: "/home/ubuntu/marketprism/services/message-broker/.venv/bin:$PATH"
    log_file: "services/message-broker/logs/broker_managed.log"
    pid_file: "services/message-broker/logs/broker.pid"
    auto_restart: true
    max_restart_attempts: 5
    restart_delay: 15
    health_check_url: "http://127.0.0.1:8086/api/v1/status"
    health_check_interval: 60
    cpu_threshold: 50.0
    memory_threshold_mb: 200
    memory_percent_threshold: 5.0
    max_uptime_hours: 48

  data-collector:
    command: "python3 services/data-collector/unified_collector_main.py"
    working_dir: "/home/ubuntu/marketprism"
    env_vars:
      COLLECTOR_ENABLE_HTTP: "0"
      PYTHONPATH: "/home/ubuntu/marketprism"
      VIRTUAL_ENV: "/home/ubuntu/marketprism/services/data-collector/.venv"
      PATH: "/home/ubuntu/marketprism/services/data-collector/.venv/bin:$PATH"
    log_file: "services/data-collector/logs/collector_managed.log"
    pid_file: "services/data-collector/logs/collector.pid"
    auto_restart: true
    max_restart_attempts: 3
    restart_delay: 20
    health_check_interval: 300  # 5分钟检查一次，因为数据收集器CPU使用率波动较大
    cpu_threshold: 75.0  # 提高阈值，避免误报
    memory_threshold_mb: 400
    memory_percent_threshold: 8.0
    max_uptime_hours: 24  # 24小时自动重启，防止内存泄漏

  data-storage-service:
    command: "python3 services/data-storage-service/main.py"
    working_dir: "/home/ubuntu/marketprism"
    env_vars:
      PYTHONPATH: "/home/ubuntu/marketprism"
      VIRTUAL_ENV: "/home/ubuntu/marketprism/services/data-storage-service/.venv"
      PATH: "/home/ubuntu/marketprism/services/data-storage-service/.venv/bin:$PATH"
      CLICKHOUSE_HOST: "127.0.0.1"
      CLICKHOUSE_HTTP_PORT: "8123"
      CLICKHOUSE_TCP_PORT: "9000"
      CLICKHOUSE_DATABASE: "marketprism_hot"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_TIMEOUT: "30"
      CLICKHOUSE_MAX_RETRIES: "3"
    log_file: "services/data-storage-service/logs/storage_managed.log"
    pid_file: "services/data-storage-service/logs/storage.pid"
    auto_restart: true
    max_restart_attempts: 5
    restart_delay: 10
    health_check_url: "http://127.0.0.1:8081/health"
    health_check_interval: 120  # 2分钟检查一次
    cpu_threshold: 30.0
    memory_threshold_mb: 300
    memory_percent_threshold: 6.0
    max_uptime_hours: 48

# 全局配置
global_settings:
  # 日志配置
  log_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 监控配置
  enable_health_monitoring: true
  health_check_timeout: 10
  
  # 告警配置
  alert_cpu_threshold: 90.0
  alert_memory_threshold: 80.0
  alert_disk_threshold: 85.0
  
  # 系统资源限制
  max_system_cpu: 95.0
  max_system_memory: 90.0
  
  # 自动重启策略
  enable_auto_restart: true
  restart_on_memory_leak: true
  restart_on_high_cpu: true
  restart_on_long_uptime: true
  
  # 故障恢复
  enable_failover: false
  backup_instances: []
  
  # 数据备份
  enable_data_backup: false
  backup_interval_hours: 24
  backup_retention_days: 7

# 监控指标配置
monitoring:
  # 系统指标
  system_metrics:
    - cpu_usage
    - memory_usage
    - disk_usage
    - network_io
    - load_average
  
  # 应用指标
  application_metrics:
    - process_count
    - thread_count
    - file_descriptors
    - connection_count
    - queue_size
  
  # 业务指标
  business_metrics:
    - message_throughput
    - data_processing_rate
    - error_rate
    - latency
    - availability
  
  # 告警规则
  alert_rules:
    - name: "high_cpu_usage"
      condition: "cpu_usage > 85"
      duration: "5m"
      severity: "warning"
    
    - name: "critical_cpu_usage"
      condition: "cpu_usage > 95"
      duration: "2m"
      severity: "critical"
    
    - name: "high_memory_usage"
      condition: "memory_usage > 80"
      duration: "10m"
      severity: "warning"
    
    - name: "memory_leak_detected"
      condition: "memory_growth_rate > 10MB/hour"
      duration: "1h"
      severity: "warning"
    
    - name: "service_down"
      condition: "service_status != 'running'"
      duration: "30s"
      severity: "critical"
    
    - name: "data_processing_lag"
      condition: "processing_lag > 60s"
      duration: "5m"
      severity: "warning"

# 日志轮转配置
log_rotation:
  max_size: "100MB"
  backup_count: 10
  rotation_interval: "daily"
  compression: true
  
# 性能调优配置
performance_tuning:
  # 进程优先级
  process_priority:
    message-broker: 0      # 正常优先级
    data-collector: -5     # 稍高优先级
    data-storage-service: 5 # 稍低优先级
  
  # 资源限制
  resource_limits:
    max_cpu_percent: 80
    max_memory_mb: 1024
    max_file_descriptors: 65536
  
  # 网络优化
  network_optimization:
    tcp_keepalive: true
    tcp_nodelay: true
    connection_pool_size: 100
  
  # 数据库优化
  database_optimization:
    connection_pool_size: 20
    query_timeout: 30
    batch_size: 1000
    max_retries: 3
