## MarketPrism 分层数据存储配置
## 版本: 1.0.0
## 最后更新: 2025-05-11

storage:
  # 热存储配置 (云服务器ClickHouse)
  hot_storage:
    host: "clickhouse"                   # 云服务器ClickHouse主机名或IP
    port: 9000                           # ClickHouse TCP端口
    database: "marketprism"              # 数据库名
    user: "default"                      # 用户名
    password: ""                         # 密码
    retention_days: 14                   # 热存储保留天数
    
  # 冷存储配置 (本地NAS ClickHouse)
  cold_storage:
    enabled: true                        # 是否启用冷存储
    host: "nas-clickhouse.local"         # NAS上的ClickHouse主机名或IP
    port: 9000                           # ClickHouse TCP端口
    database: "marketprism"              # 数据库名
    user: "default"                      # 用户名
    password: ""                         # 密码
    
  # 归档器配置
  archiver:
    schedule: "0 2 * * *"                # cron表达式，每天凌晨2点执行归档
    batch_size: 100000                   # 每批处理的数据量
    verify_archive: true                 # 是否验证数据是否成功归档
    parallel_tables: 1                   # 同时处理的表数量
    
  # 清理配置
  cleanup:
    enabled: true                        # 是否启用自动清理
    schedule: "0 3 * * *"                # cron表达式，每天凌晨3点执行清理
    max_age_days: 90                     # 最大保留天数，超过此天数的数据将被清理
    disk_threshold: 80                   # 磁盘使用率阈值，达到此值时才执行清理
    batch_size: 100000                   # 每批处理的数据量
    
  # 归档表配置
  tables:
    trades:                              # 交易数据表
      enabled: true                      # 是否归档该表
      retention_days: 14                 # 覆盖全局保留天数设置
      priority: 1                        # 归档优先级，数字越小优先级越高
      cleanup_enabled: true              # 是否清理该表过期数据
      cleanup_age_days: 90               # 表特定的清理保留天数
      
    depth:                               # 深度数据表
      enabled: true
      retention_days: 7                  # 深度数据只保留7天
      priority: 2
      cleanup_enabled: true              # 是否清理该表过期数据
      cleanup_age_days: 60               # 深度数据清理阈值60天
      
    book_ticker:                         # 最优买卖价表
      enabled: true
      retention_days: 7
      priority: 3
      cleanup_enabled: true
      cleanup_age_days: 30               # 最优买卖价数据清理阈值30天
      
    liquidation:                         # 强平订单表
      enabled: true
      retention_days: 30                 # 强平数据保留30天
      priority: 4
      cleanup_enabled: true
      cleanup_age_days: 180              # 强平数据清理阈值180天
      
    option_vol:                          # 期权波动率表
      enabled: true
      retention_days: 30                 # 波动率数据保留30天
      priority: 5
      cleanup_enabled: true
      cleanup_age_days: 365              # 波动率数据清理阈值365天 