# MarketPrism TDD 测试配置
# 真实环境测试配置，支持代理和真实API连接

# 网络代理配置
proxy:
  enabled: true
  http_proxy: "http://127.0.0.1:7890"  # 根据实际代理修改
  https_proxy: "http://127.0.0.1:7890"
  no_proxy: "localhost,127.0.0.1,::1"

# 环境配置
environment:
  mode: "test"
  debug: true
  log_level: "DEBUG"

# 测试环境配置
test_environment:
  mode: "real_api"  # real_api | simulation
  log_level: "DEBUG"
  timeout: 30
  retry_attempts: 3
  parallel_tests: false  # 初期使用串行测试确保稳定性

# 交易所API配置 (测试网络)
exchanges:
  binance:
    testnet: true
    base_url: "https://testnet.binance.vision"
    ws_url: "wss://testnet.binance.vision/ws"
    api_key: ""  # 测试网API密钥
    api_secret: ""
    rate_limit:
      requests_per_minute: 1200
      weight_per_minute: 60000
      order_per_second: 10
      order_per_day: 200000
    
    # 支持的API端点配置
    endpoints:
      time: "/api/v3/time"
      exchangeInfo: "/api/v3/exchangeInfo"
      depth: "/api/v3/depth"
      ticker_price: "/api/v3/ticker/price"
      ticker_24hr: "/api/v3/ticker/24hr"
      klines: "/api/v3/klines"
      avgPrice: "/api/v3/avgPrice"
      # 测试端点
      test_order: "/api/v3/order/test"
      account_commission: "/api/v3/account/commission"
      trading_day: "/api/v3/ticker/tradingDay"
    
    # WebSocket流配置
    websocket_streams:
      ticker: "@ticker"
      depth: "@depth"
      trade: "@trade"
      kline_1m: "@kline_1m"
      avgPrice: "@avgPrice"
    
    # 测试交易对
    test_symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "DOTUSDT", "LINKUSDT"]
    
  okx:
    testnet: false  # OKX主要使用生产环境的公共API
    base_url: "https://www.okx.com"
    ws_url: "wss://ws.okx.com:8443/ws/v5/public"
    api_key: ""  # 测试用API密钥
    api_secret: ""
    passphrase: ""
    rate_limit:
      requests_per_second: 20
      burst_requests: 40
    
    # 支持的API端点配置
    endpoints:
      time: "/api/v5/public/time"
      instruments: "/api/v5/public/instruments"
      ticker: "/api/v5/market/ticker"
      depth: "/api/v5/market/books"
      trades: "/api/v5/market/trades"
      candles: "/api/v5/market/candles"
      index_tickers: "/api/v5/market/index-tickers"
      funding_rate: "/api/v5/public/funding-rate"
      
    # WebSocket频道配置  
    websocket_channels:
      tickers: "tickers"
      books: "books"
      trades: "trades"
      candle1m: "candle1m"
      index_tickers: "index-tickers"
      funding_rate: "funding-rate"
    
    # 测试交易对 (OKX格式)
    test_symbols: ["BTC-USDT", "ETH-USDT", "ADA-USDT", "DOT-USDT", "LINK-USDT"]
    
    # 产品类型
    instrument_types: ["SPOT", "MARGIN", "SWAP", "FUTURES", "OPTION"]

# 数据库配置 (测试实例)
databases:
  clickhouse:
    host: "localhost"
    port: 8123
    database: "marketprism_test"
    user: "test_user"
    password: "test_password"
    
  redis:
    host: "localhost"
    port: 6379
    db: 1  # 使用DB1作为测试数据库
    password: ""

# 消息队列配置
message_broker:
  nats:
    url: "nats://localhost:4222"
    cluster_id: "test_cluster"
    client_id: "test_client"
    streams:
      test_market_data: "TEST_MARKET_DATA"
      test_system_events: "TEST_SYSTEM_EVENTS"

# 微服务配置
services:
  api_gateway:
    host: "localhost"
    port: 8080
    health_endpoint: "/health"
    
  market_data_collector:
    host: "localhost"
    port: 8081
    health_endpoint: "/health"
    
  data_storage:
    host: "localhost"
    port: 8082
    health_endpoint: "/health"
    
  monitoring:
    host: "localhost"
    port: 8083
    health_endpoint: "/health"
    
  scheduler:
    host: "localhost"
    port: 8084
    health_endpoint: "/health"
    
  message_broker:
    host: "localhost"
    port: 8085
    health_endpoint: "/health"

# TDD测试配置
tdd_config:
  test_data_cleanup: true  # 每次测试后清理数据
  real_data_collection: true  # 使用真实市场数据
  performance_benchmarks: true  # 包含性能基准测试
  error_injection: true  # 错误注入测试
  
  # 测试阶段配置
  phases:
    unit_tests:
      enabled: true
      timeout: 10
      
    integration_tests:
      enabled: true
      timeout: 60
      
    e2e_tests:
      enabled: true
      timeout: 300
      
    performance_tests:
      enabled: true
      timeout: 600

# 测试数据配置
test_data:
  symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT"]
  exchanges: ["binance"]
  collection_duration: 30  # 秒
  sample_size: 100
  
# 监控和告警配置
monitoring:
  enabled: true
  metrics_endpoint: "http://localhost:8083/metrics"
  alert_webhook: ""
  
# 日志配置
logging:
  level: "DEBUG"
  format: "structured"
  output: "console"
  file_rotation: true
  max_size: "100MB"