# MarketPrism 统一交易数据管道配置
# 配置交易数据的采集、标准化、存储和分析流程

# NATS连接配置
nats:
  servers:
    - "nats://localhost:4222"
  
  # 发布配置
  publishers:
    trade_data:
      stream: "unified-trade-data"
      subjects:
        # 原始数据主题
        binance_spot: "trades.binance.spot.{symbol}"
        binance_futures: "trades.binance.futures.{symbol}"
        okx_spot: "trades.okx.spot.{symbol}"
        okx_swap: "trades.okx.swap.{symbol}"
        okx_futures: "trades.okx.futures.{symbol}"
        
        # 标准化数据主题
        normalized: "trades.normalized.{exchange}.{trade_type}.{currency}"
        
        # 告警主题
        alerts: "trades.alerts.{alert_type}.{exchange}.{currency}"
  
  # 消费者配置
  consumers:
    clickhouse_writer:
      stream: "unified-trade-data"
      durable_name: "trades-clickhouse"
      subject_filter: "trades.normalized.>"
      batch_size: 1000
      max_wait: "1s"
      
    realtime_monitor:
      stream: "unified-trade-data"
      durable_name: "trades-monitor"
      subject_filter: "trades.normalized.>"
      batch_size: 100
      max_wait: "100ms"
      
    arbitrage_detector:
      stream: "unified-trade-data"
      durable_name: "trades-arbitrage"
      subject_filter: "trades.normalized.>"
      batch_size: 50
      max_wait: "50ms"

# ClickHouse连接配置
clickhouse:
  host: "localhost"
  port: 9000
  database: "marketprism"
  username: "default"
  password: ""
  
  # 写入配置
  write_settings:
    table: "unified_trade_data"
    batch_size: 1000
    flush_interval: "5s"
    max_retries: 3
    retry_delay: "1s"
    
  # 查询配置
  query_settings:
    max_execution_time: 30
    max_memory_usage: "1GB"
    readonly: 1

# 数据处理配置
data_processing:
  # 标准化器配置
  normalizers:
    binance_spot:
      enabled: true
      class: "normalize_binance_spot_trade"
      validation:
        required_fields: ["s", "t", "p", "q", "T", "m"]
        price_range: [0.000001, 1000000]
        quantity_range: [0.000001, 1000000000]
        
    binance_futures:
      enabled: true
      class: "normalize_binance_futures_trade"
      validation:
        required_fields: ["s", "a", "p", "q", "T", "m", "f", "l"]
        price_range: [0.000001, 1000000]
        quantity_range: [0.000001, 1000000000]
        
    okx_unified:
      enabled: true
      class: "normalize_okx_trade"
      validation:
        required_fields: ["instId", "tradeId", "px", "sz", "side", "ts"]
        price_range: [0.000001, 1000000]
        quantity_range: [0.000001, 1000000000]
  
  # 数据质量检查
  quality_checks:
    enabled: true
    checks:
      - name: "price_validation"
        condition: "price > 0 AND price < 1000000"
        action: "reject"
        
      - name: "quantity_validation"
        condition: "quantity > 0 AND quantity < 1000000000"
        action: "reject"
        
      - name: "timestamp_validation"
        condition: "timestamp > now() - INTERVAL 1 HOUR AND timestamp <= now()"
        action: "warn"
        
      - name: "trade_id_validation"
        condition: "trade_id != ''"
        action: "reject"
        
      - name: "side_validation"
        condition: "side IN ('buy', 'sell')"
        action: "reject"

# 监控和告警配置
monitoring:
  # 性能监控
  performance:
    enabled: true
    metrics:
      - name: "processing_latency"
        threshold: 1000  # 毫秒
        action: "alert"
        
      - name: "data_loss_rate"
        threshold: 0.01  # 1%
        action: "alert"
        
      - name: "error_rate"
        threshold: 0.05  # 5%
        action: "alert"
  
  # 数据质量监控
  data_quality:
    enabled: true
    checks:
      - name: "invalid_data_rate"
        threshold: 0.02  # 2%
        action: "alert"
        
      - name: "missing_data_rate"
        threshold: 0.01  # 1%
        action: "alert"
        
      - name: "duplicate_data_rate"
        threshold: 0.005  # 0.5%
        action: "warn"
  
  # 业务监控
  business:
    enabled: true
    alerts:
      - name: "large_trade_detection"
        condition: "quote_quantity > 100000"  # 大于10万USDT
        action: "notify"
        
      - name: "price_spike_detection"
        condition: "price_change_percent > 5"  # 价格变动超过5%
        action: "alert"
        
      - name: "volume_surge_detection"
        condition: "volume_change_percent > 200"  # 交易量激增200%
        action: "notify"
        
      - name: "arbitrage_opportunity"
        condition: "price_spread_percent > 1"  # 套利机会超过1%
        action: "notify"

# 数据保留策略
retention:
  # 原始数据保留
  raw_data:
    hot_storage: "7d"    # 热存储7天
    cold_storage: "30d"  # 冷存储30天
    archive: "365d"      # 归档1年
    
  # 聚合数据保留
  aggregated_data:
    minute_stats: "90d"   # 分钟级统计90天
    hourly_stats: "365d"  # 小时级统计1年
    daily_stats: "1095d"  # 日级统计3年

# 性能优化配置
performance:
  # 并发配置
  concurrency:
    normalizer_workers: 4
    writer_workers: 2
    monitor_workers: 1
    
  # 缓存配置
  cache:
    enabled: true
    size: "512MB"
    ttl: "5m"
    
  # 批处理配置
  batching:
    enabled: true
    size: 1000
    timeout: "1s"
    
  # 压缩配置
  compression:
    enabled: true
    algorithm: "lz4"
    level: 1

# 日志配置
logging:
  level: "INFO"
  format: "json"
  output: "stdout"
  
  # 日志轮转
  rotation:
    enabled: true
    max_size: "100MB"
    max_files: 10
    max_age: "7d"
  
  # 特定组件日志级别
  components:
    normalizer: "INFO"
    writer: "INFO"
    monitor: "WARN"
    arbitrage: "INFO"

# 健康检查配置
health_check:
  enabled: true
  interval: "30s"
  timeout: "5s"
  
  checks:
    - name: "nats_connection"
      type: "nats"
      critical: true
      
    - name: "clickhouse_connection"
      type: "clickhouse"
      critical: true
      
    - name: "data_processing"
      type: "custom"
      critical: false
      
    - name: "memory_usage"
      type: "system"
      threshold: "80%"
      critical: false

# 开发和调试配置
debug:
  enabled: false
  
  # 数据采样
  sampling:
    enabled: false
    rate: 0.1  # 10%采样率
    
  # 性能分析
  profiling:
    enabled: false
    cpu: true
    memory: true
    
  # 数据导出
  export:
    enabled: false
    format: "json"
    destination: "/tmp/trade_data_export"
