# MarketPrism 统一存储配置
# 整合了data_archiver和core/storage的所有配置

# 基础存储配置
storage:
  # 存储类型：hot, cold, simple, hybrid
  type: "hot"
  enabled: true
  
  # ClickHouse配置
  clickhouse:
    host: "localhost"
    port: 8123
    user: "default"
    password: ""
    database: "marketprism"
    
    # 连接池配置
    connection_pool:
      size: 10
      max_retries: 3
    
    # 性能配置
    performance:
      batch_size: 1000
      flush_interval: 5
      
  # Redis配置（热存储）
  redis:
    enabled: true
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    cache:
      default_ttl: 3600
      
  # 热存储配置
  hot_storage:
    retention_days: 14
    hot_data_ttl: 3600
    
  # 冷存储配置
  cold_storage:
    enabled: true
    host: "localhost"
    port: 8124
    database: "marketprism_cold"
    cold_data_ttl: 2592000  # 30天
    
    # 分区和压缩
    partitioning:
      partition_by: "toYYYYMM(timestamp)"
      
    compression:
      enabled: true
      codec: "LZ4"
      
  # 归档配置（整合自data_archiver）
  archiving:
    enabled: true
    schedule: "0 2 * * *"  # 每天凌晨2点
    retention_days: 14
    batch_size: 100000
    max_retries: 3
    
    # 归档策略
    tables:
      trades:
        enabled: true
        priority: 1
        retention_days: 7
        enabled: true
        priority: 2
        retention_days: 14
      orderbooks:
        enabled: true
        priority: 3
        retention_days: 3
        
  # 清理配置（整合自data_archiver）
  cleanup:
    enabled: true
    schedule: "0 3 * * *"  # 每天凌晨3点
    max_age_days: 90
    disk_threshold: 80
    batch_size: 100000
    
    # 智能清理
    smart_cleanup: true
    critical_threshold: 90
    aggressive_threshold: 95
    
    # 清理策略
    tables:
      trades:
        cleanup_enabled: true
        max_age_days: 90
        cleanup_enabled: true
        max_age_days: 180
      orderbooks:
        cleanup_enabled: true
        max_age_days: 30

# 服务配置（整合自DataArchiverService）
service:
  # 心跳配置
  heartbeat_interval: 60
  
  # NATS配置
  nats:
    enabled: false
    url: "nats://localhost:4222"
    
    # 消息处理
    message_handlers:
      trades: "market.trades.*"
      orderbooks: "market.orderbooks.*"
      
  # 健康检查
  health_check:
    interval: 60
    timeout: 30
    
# 监控配置
monitoring:
  # Prometheus指标
  prometheus:
    enabled: true
    port: 9090
    
  # 日志配置
  logging:
    level: "INFO"
    file: "logs/storage_manager.log"
    rotation: "1 day"
    retention: "30 days"

# 安全配置
security:
  # 数据加密
  encryption:
    enabled: false
    algorithm: "AES-256"
    
  # 访问控制
  access_control:
    enabled: false
    
# 性能优化配置
optimization:
  # 缓存策略
  cache_strategy: "write_through"  # write_through, write_back, write_around
  memory_cache_enabled: true
  
  # 连接复用
  connection_pooling: true
  
  # 批处理优化
  batch_optimization: true