# MarketPrism 交易所API代理配置
# 简单优雅的统一API管理

# 基础配置
proxy_settings:
  mode: "auto"  # auto, unified, distributed
  auto_detect_ip: true
  max_request_history: 10000
  health_check_interval: 60

# IP资源配置
ip_resources:
  # 单IP模式示例
  single_ip:
    - ip: "auto-detect"  # 自动检测当前IP
      location: "local"
      max_weight_per_minute: 6000
      
  # 多IP模式示例（当有多个服务器时）
  multi_ip:
    - ip: "192.168.1.100"
      location: "server-1"
      max_weight_per_minute: 6000
      provider: "aws"
      
    - ip: "192.168.1.101"
      location: "server-2"
      max_weight_per_minute: 6000
      provider: "gcp"
      
    - ip: "192.168.1.102"
      location: "server-3"
      max_weight_per_minute: 6000
      provider: "azure"

# 交易所配置
exchanges:
  binance:
    base_url: "https://api.binance.com"
    max_weight_per_minute: 6000
    weight_reset_interval: 60
    health_check_endpoint: "/api/v3/ping"
    
  okx:
    base_url: "https://www.okx.com"
    max_weight_per_minute: 3000
    weight_reset_interval: 60
    health_check_endpoint: "/api/v5/public/time"
    
  deribit:
    base_url: "https://www.deribit.com"
    max_weight_per_minute: 2000
    weight_reset_interval: 60
    health_check_endpoint: "/api/v2/public/get_time"

# 超限处理策略
rate_limit_handling:
  # 429处理
  warning_response:
    enable_auto_retry: true
    max_retries: 3
    backoff_strategy: "exponential"  # linear, exponential
    base_delay: 1.0
    max_delay: 60.0
    
  # 418处理  
  ban_response:
    enable_ip_rotation: true
    fallback_to_other_ips: true
    ban_recovery_strategy: "wait"  # wait, rotate
    default_ban_duration: 120  # 秒
    
  # 预防策略
  prevention:
    weight_usage_warning_threshold: 0.8  # 80%
    weight_usage_critical_threshold: 0.95  # 95%
    enable_request_queuing: true
    queue_max_size: 1000

# 监控和告警
monitoring:
  enable_metrics: true
  enable_health_check: true
  enable_performance_tracking: true
  
  # 告警阈值
  alerts:
    error_rate_threshold: 0.1  # 10%
    response_time_threshold: 5.0  # 5秒
    ip_ban_alert: true
    weight_exhaustion_alert: true
    
  # 日志配置
  logging:
    level: "INFO"
    enable_request_logging: false  # 只记录错误和重要事件
    enable_performance_logging: true
    log_format: "json"

# 优化配置
optimization:
  # IP选择策略
  ip_selection:
    strategy: "health_weighted"  # round_robin, least_used, health_weighted
    health_score_weight: 0.7
    usage_weight: 0.3
    
  # 请求优化
  request_optimization:
    enable_connection_pooling: true
    connection_timeout: 30
    read_timeout: 30
    max_connections_per_ip: 100
    
  # 缓存配置
  caching:
    enable_response_cache: false  # API数据实时性要求高
    enable_weight_cache: true
    cache_ttl: 300

# 故障恢复
failover:
  enable_automatic_failover: true
  failover_strategy: "fast"  # fast, conservative
  
  # IP故障检测
  ip_failure_detection:
    consecutive_failures_threshold: 3
    failure_time_window: 300  # 5分钟
    recovery_probe_interval: 60
    
  # 服务降级
  degradation:
    enable_graceful_degradation: true
    reduced_rate_factor: 0.5  # 降级到50%请求量
    degradation_duration: 300  # 5分钟

# 测试配置
testing:
  enable_test_mode: false
  mock_responses: false
  simulate_rate_limits: false
  test_ip_pool:
    - "127.0.0.1"
    - "192.168.1.10"