# MarketPrism 环境变量覆盖配置
# 统一管理所有服务的环境变量覆盖规则

# 全局配置
global:
  environment: ${ENVIRONMENT:-staging}
  log_level: ${LOG_LEVEL:-INFO}
  config_factory_enabled: ${CONFIG_FACTORY_ENABLED:-true}

# ClickHouse配置覆盖
clickhouse:
  # 热存储配置
  hot_storage:
    host: ${CLICKHOUSE_HOST:-clickhouse}
    port: ${CLICKHOUSE_PORT:-8123}
    user: ${CLICKHOUSE_USER:-default}
    password: ${CLICKHOUSE_PASSWORD:-}
    database: ${CLICKHOUSE_DATABASE:-marketprism}
  
  # 冷存储配置
  cold_storage:
    host: ${COLD_CLICKHOUSE_HOST:-clickhouse}
    port: ${COLD_CLICKHOUSE_PORT:-8123}
    user: ${COLD_CLICKHOUSE_USER:-default}
    password: ${COLD_CLICKHOUSE_PASSWORD:-}
    database: ${COLD_CLICKHOUSE_DATABASE:-marketprism_cold}

# 数据库配置覆盖
database:
  postgres:
    url: postgresql://${POSTGRES_USER:-marketprism}:${POSTGRES_PASSWORD:-marketprism123}@postgres:5432/${POSTGRES_DB:-marketprism}
  
  redis:
    url: redis://:${REDIS_PASSWORD:-}@redis:6379/1

# 服务端口配置
services:
  api_gateway:
    port: ${API_GATEWAY_PORT:-8080}
  
  monitoring_alerting:
    port: ${MONITORING_PORT:-8082}
  
  data_storage_hot:
    port: ${DATA_STORAGE_PORT:-8083}
  
  data_storage_cold:
    port: ${COLD_STORAGE_PORT:-8087}
  
  market_data_collector:
    port: ${COLLECTOR_PORT:-8084}
  
  scheduler:
    port: ${SCHEDULER_PORT:-8085}
  
  message_broker:
    port: ${MESSAGE_BROKER_PORT:-8086}

# 存储模式配置
storage:
  mode: ${STORAGE_MODE:-hot}
  
  # 热存储配置
  hot:
    ttl_days: ${HOT_TTL_DAYS:-1}
    compression: ${HOT_COMPRESSION:-LZ4}
    partition_by: ${HOT_PARTITION:-toYYYYMMDD(timestamp), exchange}
  
  # 冷存储配置
  cold:
    ttl_days: ${COLD_TTL_DAYS:-365}
    compression: ${COLD_COMPRESSION:-ZSTD}
    partition_by: ${COLD_PARTITION:-toYYYYMM(timestamp), exchange}

# 数据迁移配置
migration:
  enabled: ${MIGRATION_ENABLED:-true}
  schedule: ${MIGRATION_SCHEDULE:-0 2 * * *}
  batch_size: ${MIGRATION_BATCH_SIZE:-10000}
  verification_enabled: ${MIGRATION_VERIFICATION:-true}

# 监控配置
monitoring:
  prometheus:
    enabled: ${PROMETHEUS_ENABLED:-true}
    port: ${PROMETHEUS_PORT:-9090}
  
  ui_dashboard:
    enabled: ${UI_DASHBOARD_ENABLED:-true}
    port: ${UI_DASHBOARD_PORT:-3000}

# 网络配置
network:
  name: ${NETWORK_NAME:-marketprism-network}
  
# 安全配置
security:
  enable_tls: ${ENABLE_TLS:-false}
  api_key_enabled: ${API_KEY_ENABLED:-false}
