# MarketPrism 开发环境配置
# 用于本地开发和测试

# 收集器配置
collector:
  # 基础配置
  http_port: 8080
  log_level: "DEBUG"
  enable_scheduler: true
  
  # 大户持仓比数据收集器配置
  enable_top_trader_collector: true
  top_trader_symbols:
    - "BTC-USDT"
    - "ETH-USDT"
    - "BNB-USDT"
    - "SOL-USDT"
    - "ADA-USDT"
  
  # 收集间隔配置（分钟）
  top_trader_collection_intervals:
    binance: 5  # 币安每5分钟收集一次
    okx: 5      # OKX每5分钟收集一次

# NATS配置
nats:
  servers:
    - "nats://localhost:4222"
  
  # 流配置
  streams:
    MARKET_DATA:
      subjects:
        - "market.data.trades.*"
        - "market.data.orderbook.*"
        - "market.data.klines.*"
        - "market.data.funding_rates.*"
        - "market.data.open_interest.*"
        - "market.data.liquidations.*"
        - "market.data.top_trader_long_short_ratio.*"
      
      retention: "interest"
      max_age: "24h"
      max_bytes: "1GB"
      max_msgs: 1000000
      
      storage: "file"
      replicas: 1
      
      # 消费者配置
      consumers:
        - name: "clickhouse_writer"
          durable_name: "clickhouse_writer"
          deliver_policy: "all"
          ack_policy: "explicit"
          max_deliver: 3
          ack_wait: "30s"

# 交易所配置
exchanges:
  # 币安配置
  binance:
    enabled: true
    api_key: ""  # 从环境变量获取
    api_secret: ""  # 从环境变量获取
    testnet: false
    
    # REST API配置
    rest_api:
      base_url: "https://fapi.binance.com"
      timeout: 30
      max_retries: 3
      rate_limit_per_minute: 1200
      
    # WebSocket配置
    websocket:
      base_url: "wss://fstream.binance.com"
      ping_interval: 180
      max_reconnect_attempts: 10
    
    # 支持的交易对
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "BNBUSDT"
      - "SOLUSDT"
      - "ADAUSDT"
  
  # OKX配置
  okx:
    enabled: true
    api_key: ""  # 从环境变量获取
    api_secret: ""  # 从环境变量获取
    passphrase: ""  # 从环境变量获取
    sandbox: false
    
    # REST API配置
    rest_api:
      base_url: "https://www.okx.com"
      timeout: 30
      max_retries: 3
      rate_limit_per_minute: 600
      
    # WebSocket配置
    websocket:
      base_url: "wss://ws.okx.com:8443"
      ping_interval: 30
      max_reconnect_attempts: 10
    
    # 支持的交易对
    symbols:
      - "BTC-USDT"
      - "ETH-USDT"
      - "BNB-USDT"
      - "SOL-USDT"
      - "ADA-USDT"

# ClickHouse配置
clickhouse:
  enabled: true
  host: "localhost"
  port: 9000
  database: "marketprism"
  username: "default"
  password: ""
  
  # 连接池配置
  pool_size: 10
  max_overflow: 20
  
  # 批量写入配置
  batch_size: 1000
  flush_interval: 10  # 秒

# 监控配置
monitoring:
  prometheus:
    enabled: true
    port: 9090
  
  grafana:
    enabled: true
    port: 3000

# 日志配置
logging:
  level: "DEBUG"
  format: "json"
  
  # 文件日志
  file:
    enabled: true
    path: "logs/collector.log"
    max_size: "100MB"
    backup_count: 5
  
  # 控制台日志
  console:
    enabled: true
    colored: true

# 代理配置（可选）
proxy:
  enabled: false
  http_proxy: ""
  https_proxy: ""
  no_proxy: "localhost,127.0.0.1" 