# MarketPrism订单簿管理系统 Prometheus配置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'marketprism'
    environment: 'production'

# 告警规则文件
rule_files:
  - "rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 数据抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # MarketPrism订单簿管理系统
  - job_name: 'marketprism-orderbook'
    static_configs:
      - targets: ['orderbook-manager:8081']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # NATS监控
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    scrape_interval: 15s
    metrics_path: /metrics

  # ClickHouse监控
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      query: ['SELECT * FROM system.metrics FORMAT Prometheus']

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # Docker容器监控
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s

  # 节点监控（如果安装了node_exporter）
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

# 远程写入配置（可选）
# remote_write:
#   - url: "https://your-remote-prometheus.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# 远程读取配置（可选）
# remote_read:
#   - url: "https://your-remote-prometheus.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
