global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 监控NATS
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: /
    scheme: http

  # 添加更多监控目标...
  # 如果go-collector和data-normalizer服务暴露指标，可以在这里添加 