# OKX WebSocket配置 - 基于2025年最新API文档
# 参考: https://www.okx.com/docs-v5/zh/#overview

okx_websocket:
  # 基础连接配置
  connection:
    url: "wss://ws.okx.com:8443/ws/v5/public"
    private_url: "wss://ws.okx.com:8443/ws/v5/private"
    business_url: "wss://ws.okx.com:8443/ws/v5/business"
    timeout: 30
    max_connections: 100  # OKX连接限制
    
  # OKX特定的ping/pong机制
  ping_pong:
    enabled: true
    interval: 25  # 25秒发送ping（OKX要求30秒内必须有活动）
    timeout: 5    # 5秒pong超时
    format: "string"  # OKX使用字符串格式ping
    ping_message: "ping"
    expected_pong: "pong"
    
  # 连接维护策略
  maintenance:
    heartbeat_check: true
    heartbeat_interval: 20  # 20秒检查一次
    max_idle_time: 30       # 30秒无数据触发ping
    login_required: true    # 私有频道需要登录
    
  # 重连策略
  reconnect:
    enabled: true
    initial_delay: 1        # 初始重连延迟1秒
    max_delay: 30          # 最大重连延迟30秒
    backoff_multiplier: 1.5 # 较温和的退避策略
    max_attempts: 15       # 更多重连尝试
    jitter: true
    
  # 认证配置
  authentication:
    required_for_private: true
    method: "hmac_sha256"
    fields:
      - "api_key"
      - "secret_key" 
      - "passphrase"
    login_message:
      op: "login"
      args:
        - apiKey: "{api_key}"
          passphrase: "{passphrase}"
          timestamp: "{timestamp}"
          sign: "{signature}"
          
  # 订阅管理
  subscription:
    method: "subscribe"
    unsubscribe_method: "unsubscribe"
    operation_field: "op"
    args_field: "args"
    max_subscriptions: 240  # 单连接最大订阅数
    batch_subscribe: true
    
  # 数据流配置
  streams:
    # 公共数据流
    public:
      trade: "trades"
      orderbook: "books"
      kline: "candle{interval}"
      ticker: "tickers"
      funding_rate: "funding-rate"
      open_interest: "open-interest"
      
    # 私有数据流
    private:
      account: "account"
      positions: "positions"
      orders: "orders"
      balance: "balance-and-position"
      
    # 业务数据流
    business:
      algo_orders: "algo-orders"
      advance_algo_orders: "advance-algo-orders"
      
  # 频道配置
  channels:
    public_channels:
      - "trades"
      - "books"
      - "tickers"
      - "candle1m"
      - "funding-rate"
    private_channels:
      - "account"
      - "positions"
      - "orders"
    business_channels:
      - "algo-orders"
      
  # 错误处理
  error_handling:
    auto_reconnect_on_error: true
    login_retry: true
    login_retry_delay: 5
    error_codes:
      success: "0"
      login_failed: "60009"
      invalid_op: "60012"
    retry_on_login_failure: true
    
  # 性能优化
  performance:
    buffer_size: 32768      # 32KB缓冲区
    compression: true       # OKX支持gzip压缩
    binary_data: false      # 使用JSON文本
    
  # 监控配置
  monitoring:
    connection_stats: true
    login_status_tracking: true
    subscription_health: true
    message_latency: true
    error_rate_threshold: 0.03  # 3%错误率阈值
