# MarketPrism 统一消息代理服务配置
# 与 collector 配置完全对齐，确保 JetStream 流配置一致

# 服务基础配置
service:
  name: "unified-message-broker"
  version: "1.0.0"
  environment: "production"
  port: 8086
  metrics_port: 9096
  host: "0.0.0.0"


# NATS 客户端配置（外部 NATS - 通过 Docker 启动）
nats_client:
  nats_url: "nats://127.0.0.1:4222"   # 指向本地 NATS 服务
  client_name: "unified-message-broker"
  max_reconnect_attempts: 10
  reconnect_time_wait: 2
  strict_subjects: true         # 严格对齐 subjects，清理历史 “*-data.>”

# manage_all 模式说明：JetStream 流配置的唯一事实源为 scripts/js_init_market_data.yaml；
# 本文件不再维护 streams 配置，仅用于 standalone/调试场景参考。
streams: {}


# manage_all 模式下不在 broker 层维护 LSR 订阅；由下游存储/消费方自行管理。

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9096
  health_check_interval: 30

  # 告警阈值
  alerts:
    max_memory_usage: 0.8
    max_disk_usage: 0.9
    max_connection_count: 1000
    min_available_storage: 1073741824  # 1GB

# 日志配置
logging:
  level: "INFO"
  format: "json"
  file: "logs/unified_message_broker.log"
  max_size: "100MB"
  max_files: 10

