# MarketPrism Python Collector 配置文件
# 生成时间: 2025-05-24T12:10:31.143921

# 收集器配置
collector:
  use_real_exchanges: true  # 是否使用真实交易所 (true: 真实, false: 模拟)
  log_level: "INFO"
  http_port: 8080
  metrics_port: 9090
  max_reconnect_attempts: 5
  reconnect_delay: 5
  max_concurrent_connections: 10
  message_buffer_size: 1000
  enable_scheduler: true  # 启用任务调度器

# ClickHouse直接写入配置 (可选，从ingestion迁移的功能)
clickhouse_direct_write: false  # 是否启用ClickHouse直接写入
clickhouse:
  host: "localhost"
  port: 8123
  database: "marketprism"
  user: "default"
  password: ""
  tables:
    trades: "trades"
    orderbook: "depth"
  write:
    batch_size: 1000
    interval: 5

# NATS配置
nats:
  url: "nats://localhost:4222"
  client_name: "marketprism-collector"
  streams:
    MARKET_DATA:
      name: "MARKET_DATA"
      subjects: ["market.>"]
      retention: "limits"
      max_msgs: 1000000
      max_bytes: 1073741824  # 1GB
      max_age: 86400  # 24小时
      max_consumers: 10
      replicas: 1

# 代理配置
proxy:
  enabled: true
  http_proxy: "http://127.0.0.1:1087"
  https_proxy: "http://127.0.0.1:1087"
  no_proxy: "localhost,127.0.0.1"

# 交易所配置文件列表
exchanges:
  configs:
    - "exchanges/binance_spot.yaml"
    - "exchanges/okx_spot.yaml"
    - "exchanges/deribit_derivatives.yaml"

# 环境配置
environment: "development"
debug: false
