groups:
- name: 配置一致性告警
  rules:
  - alert: 配置版本不匹配
    expr: config_version_mismatch > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "检测到配置版本不匹配"
      description: "系统中存在与当前版本({{ $value }})不匹配的配置文件，请执行配置验证"

  - alert: 已弃用服务仍在运行
    expr: deprecated_service_running > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "已弃用的服务仍在运行"
      description: "检测到已弃用的服务仍在系统中运行，请参考技术栈迁移清单进行处理"
  
  - alert: 技术栈不一致
    expr: tech_stack_inconsistency > 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "存在技术栈不一致问题"
      description: "系统配置与当前技术栈不一致，可能会导致功能异常，请执行'python scripts/config_validator.py'进行检查" 