# MarketPrism统一NATS容器 - Docker Compose配置
# 简化架构：单一NATS容器集成所有Message Broker功能

version: '3.8'

services:
  # ==================== 统一NATS服务 ====================
  nats-unified:
    build:
      context: .
      dockerfile: Dockerfile.unified
      args:
        BUILD_DATE: ${BUILD_DATE:-}
        VCS_REF: ${VCS_REF:-}
        VERSION: ${VERSION:-2.0.0-unified}
    
    container_name: marketprism-nats-unified
    hostname: nats
    restart: unless-stopped
    
    # ==================== 端口映射 ====================
    ports:
      - "${NATS_PORT:-4222}:4222"      # NATS客户端端口
      - "${NATS_HTTP_PORT:-8222}:8222" # HTTP监控端口
      - "${NATS_CLUSTER_PORT:-6222}:6222" # 集群端口（可选）
    
    # ==================== 环境变量配置 ====================
    environment:
      # 基础服务配置
      - NATS_SERVER_NAME=${NATS_SERVER_NAME:-marketprism-nats-unified}
      - NATS_HOST=${NATS_HOST:-0.0.0.0}
      - NATS_PORT=${NATS_PORT:-4222}
      - NATS_HTTP_PORT=${NATS_HTTP_PORT:-8222}
      - NATS_CLUSTER_PORT=${NATS_CLUSTER_PORT:-6222}
      
      # JetStream配置
      - JETSTREAM_ENABLED=${JETSTREAM_ENABLED:-true}
      - JETSTREAM_STORE_DIR=${JETSTREAM_STORE_DIR:-/data/jetstream}
      - JETSTREAM_MAX_MEMORY=${JETSTREAM_MAX_MEMORY:-1GB}
      - JETSTREAM_MAX_FILE=${JETSTREAM_MAX_FILE:-10GB}
      
      # 流配置（支持所有7种数据类型）
      - STREAM_NAME=${STREAM_NAME:-MARKET_DATA}
      - STREAM_MAX_CONSUMERS=${STREAM_MAX_CONSUMERS:-50}
      - STREAM_MAX_MSGS=${STREAM_MAX_MSGS:-1000000}
      - STREAM_MAX_BYTES=${STREAM_MAX_BYTES:-1073741824}
      - STREAM_MAX_AGE=${STREAM_MAX_AGE:-7200}
      - STREAM_REPLICAS=${STREAM_REPLICAS:-1}
      
      # 日志配置
      - NATS_LOG_FILE=${NATS_LOG_FILE:-/var/log/nats/nats.log}
      - NATS_LOG_TIME=${NATS_LOG_TIME:-true}
      - NATS_DEBUG=${NATS_DEBUG:-false}
      - NATS_TRACE=${NATS_TRACE:-false}
      
      # 监控配置
      - MONITORING_ENABLED=${MONITORING_ENABLED:-true}
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL:-60}
      
      # 连接配置
      - NATS_MAX_CONNECTIONS=${NATS_MAX_CONNECTIONS:-1000}
      - NATS_MAX_CONTROL_LINE=${NATS_MAX_CONTROL_LINE:-4096}
      - NATS_MAX_PAYLOAD=${NATS_MAX_PAYLOAD:-1MB}
      - NATS_MAX_PENDING=${NATS_MAX_PENDING:-64MB}
      
      # 认证配置（生产环境建议启用）
      - NATS_AUTH_ENABLED=${NATS_AUTH_ENABLED:-false}
      - NATS_AUTH_USERNAME=${NATS_AUTH_USERNAME:-}
      - NATS_AUTH_PASSWORD=${NATS_AUTH_PASSWORD:-}
      - NATS_AUTH_TOKEN=${NATS_AUTH_TOKEN:-}
      
      # 集群配置（多节点部署时启用）
      - NATS_CLUSTER_ENABLED=${NATS_CLUSTER_ENABLED:-false}
      - NATS_CLUSTER_NAME=${NATS_CLUSTER_NAME:-marketprism-cluster}
      - NATS_CLUSTER_ROUTES=${NATS_CLUSTER_ROUTES:-}
      
      # 操作配置
      - INIT_TIMEOUT=${INIT_TIMEOUT:-60}
      - NATS_CONNECT_TIMEOUT=${NATS_CONNECT_TIMEOUT:-10}
      - NATS_MAX_RECONNECT=${NATS_MAX_RECONNECT:-10}
    
    # ==================== 数据卷挂载 ====================
    volumes:
      # JetStream数据持久化
      - nats_unified_data:/data/jetstream
      # 日志持久化
      - nats_unified_logs:/var/log/nats
      # 配置文件挂载（可选）
      - ./config:/app/config:ro
    
    # ==================== 健康检查 ====================
    healthcheck:
      test: ["CMD", "/app/scripts/health_check.sh", "quick"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # ==================== 资源限制 ====================
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
          cpus: ${CPU_LIMIT:-2.0}
        reservations:
          memory: ${MEMORY_RESERVATION:-512M}
          cpus: ${CPU_RESERVATION:-0.5}
    
    # ==================== 网络配置 ====================
    networks:
      - marketprism-network
    
    # ==================== 日志配置 ====================
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-50m}"
        max-file: "${LOG_MAX_FILE:-5}"
        labels: "service=nats-unified"

# ==================== 网络配置 ====================
networks:
  marketprism-network:
    driver: bridge
    name: marketprism-network
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.20.0.0/16}

# ==================== 数据卷配置 ====================
volumes:
  # JetStream数据卷
  nats_unified_data:
    driver: local
    name: marketprism-nats-unified-data
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR:-./data}/jetstream
  
  # 日志数据卷
  nats_unified_logs:
    driver: local
    name: marketprism-nats-unified-logs
    driver_opts:
      type: none
      o: bind
      device: ${LOG_DIR:-./logs}/nats

# ==================== 扩展配置 ====================
# 开发环境配置
x-development: &development
  environment:
    - NATS_DEBUG=true
    - NATS_TRACE=false
    - JETSTREAM_MAX_MEMORY=512MB
    - JETSTREAM_MAX_FILE=2GB
    - STREAM_MAX_MSGS=100000
    - STREAM_MAX_BYTES=104857600
    - HEALTH_CHECK_INTERVAL=30

# 生产环境配置
x-production: &production
  environment:
    - NATS_DEBUG=false
    - NATS_TRACE=false
    - JETSTREAM_MAX_MEMORY=2GB
    - JETSTREAM_MAX_FILE=20GB
    - STREAM_MAX_MSGS=10000000
    - STREAM_MAX_BYTES=10737418240
    - HEALTH_CHECK_INTERVAL=60
    - NATS_AUTH_ENABLED=true
  deploy:
    resources:
      limits:
        memory: 4G
        cpus: 4.0
      reservations:
        memory: 1G
        cpus: 1.0

# 测试环境配置
x-testing: &testing
  environment:
    - NATS_DEBUG=true
    - NATS_TRACE=true
    - JETSTREAM_MAX_MEMORY=256MB
    - JETSTREAM_MAX_FILE=1GB
    - STREAM_MAX_MSGS=10000
    - STREAM_MAX_BYTES=10485760
    - HEALTH_CHECK_INTERVAL=15
  deploy:
    resources:
      limits:
        memory: 1G
        cpus: 1.0
