global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  # 自身监控
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter 监控
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Go Collector 监控
  - job_name: "go-collector"
    static_configs:
      - targets: ["go-collector:8081"]

  # 数据归档服务监控
  - job_name: "data-archiver"
    static_configs:
      - targets: ["data-archiver:8082"]
    
  # Python数据收集器监控 (替代原ingestion)
  - job_name: "python-collector"
    static_configs:
      - targets: ["python-collector:8080"]
    metrics_path: /metrics
    
  # NATS 监控
  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]
    metrics_path: /metrics
    
  # ClickHouse 监控
  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:9363"]
    metrics_path: /metrics