name: MarketPrism Validation

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Config consistency check (NATS optional)
        run: |
          set -e
          echo "Running config consistency check..."
          python scripts/config_consistency_check.py || true

      - name: Production E2E validate (dry, optional)
        run: |
          echo "Running production_e2e_validate (may be partial on CI)"
          python scripts/production_e2e_validate.py || true

      - name: Comprehensive validation (short, skip heavy IO)
        run: |
          echo "Running short comprehensive validation (2 minutes, no stress)"
          python scripts/comprehensive_system_validation.py --duration 2 || true

      - name: Summarize reports if generated
        run: |
          ls -1 validation_report_*.json 2>/dev/null || echo "No report files generated"
          if ls validation_report_*.json >/dev/null 2>&1; then
            echo "Latest report summary:";
            python - << 'PY'
import glob, json
files = sorted(glob.glob('validation_report_*.json'))
if files:
    with open(files[-1], 'r', encoding='utf-8') as f:
        data = json.load(f)
    s = data.get('validation_summary', {})
    print({k: s.get(k) for k in ['timestamp','duration_minutes','total_tests','passed_tests','warning_tests','failed_tests']})
PY
          fi

      - name: Upload validation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-artifacts
          path: |
            validation_report_*.json
            validation_run.log
          if-no-files-found: ignore

