# MarketPrism Grafana数据源配置 - 生产环境
# 解决Docker网络集成问题

apiVersion: 1

datasources:
  # 主要Prometheus数据源 - 修复Docker网络问题
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://marketprism-prometheus:9090  # 使用实际容器名
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
    secureJsonData: {}

  # MarketPrism监控服务直接数据源
  - name: MarketPrism-Direct
    type: prometheus
    access: proxy
    url: http://marketprism-monitoring:8082/metrics
    isDefault: false
    editable: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: marketprism2024!
    jsonData:
      timeInterval: "10s"
      httpMethod: "GET"
      manageAlerts: false
      prometheusType: Prometheus
