# MarketPrism 智能告警规则
# 三级告警体系：P1(严重) / P2(重要) / P3(一般)

groups:
  # === P1级告警 (严重 - 立即响应) ===
  - name: marketprism.critical
    interval: 30s
    rules:
      # 系统完全不可用
      - alert: MarketPrismSystemDown
        expr: up{job="marketprism-collector"} == 0
        for: 1m
        labels:
          severity: critical
          priority: P1
          component: system
        annotations:
          summary: "MarketPrism收集器服务不可用"
          description: "MarketPrism收集器服务已离线超过1分钟，系统完全不可用"
          runbook_url: "https://docs.marketprism.com/runbooks/system-down"
          action: "立即检查服务状态并重启"

      # 所有交易所连接断开
      - alert: MarketPrismAllExchangesDisconnected
        expr: sum(marketprism_exchange_connection_status) == 0
        for: 2m
        labels:
          severity: critical
          priority: P1
          component: exchange
        annotations:
          summary: "所有交易所连接断开"
          description: "所有交易所连接已断开超过2分钟，数据收集完全停止"
          runbook_url: "https://docs.marketprism.com/runbooks/exchange-disconnected"
          action: "检查网络连接和API密钥配置"

      # 消息处理完全停止
      - alert: MarketPrismMessageProcessingStopped
        expr: rate(marketprism_collector_messages_total[5m]) == 0
        for: 5m
        labels:
          severity: critical
          priority: P1
          component: processing
        annotations:
          summary: "消息处理完全停止"
          description: "系统在过去5分钟内没有处理任何消息"
          runbook_url: "https://docs.marketprism.com/runbooks/processing-stopped"
          action: "检查收集器状态和交易所连接"

      # NATS连接断开
      - alert: MarketPrismNATSDisconnected
        expr: marketprism_nats_connection_status == 0
        for: 1m
        labels:
          severity: critical
          priority: P1
          component: nats
        annotations:
          summary: "NATS消息队列连接断开"
          description: "NATS连接已断开超过1分钟，消息发布停止"
          runbook_url: "https://docs.marketprism.com/runbooks/nats-disconnected"
          action: "检查NATS服务状态和网络连接"

  # === P2级告警 (重要 - 30分钟内响应) ===
  - name: marketprism.warning
    interval: 60s
    rules:
      # 错误率过高
      - alert: MarketPrismHighErrorRate
        expr: |
          (
            sum(rate(marketprism_collector_errors_total[5m])) by (exchange) /
            sum(rate(marketprism_collector_messages_total[5m])) by (exchange)
          ) * 100 > 5
        for: 10m
        labels:
          severity: warning
          priority: P2
          component: processing
        annotations:
          summary: "错误率过高: {{ $labels.exchange }}"
          description: "交易所 {{ $labels.exchange }} 错误率为 {{ $value | humanizePercentage }}，超过5%阈值"
          runbook_url: "https://docs.marketprism.com/runbooks/high-error-rate"
          action: "检查交易所API状态和网络连接"

      # 处理延迟过高
      - alert: MarketPrismHighProcessingLatency
        expr: |
          histogram_quantile(0.95, 
            sum(rate(marketprism_collector_processing_duration_seconds_bucket[5m])) by (le, exchange)
          ) > 1.0
        for: 15m
        labels:
          severity: warning
          priority: P2
          component: performance
        annotations:
          summary: "处理延迟过高: {{ $labels.exchange }}"
          description: "交易所 {{ $labels.exchange }} 处理延迟P95为 {{ $value | humanizeDuration }}，超过1秒阈值"
          runbook_url: "https://docs.marketprism.com/runbooks/high-latency"
          action: "检查系统负载和网络延迟"

      # 单个交易所连接断开
      - alert: MarketPrismExchangeDisconnected
        expr: marketprism_exchange_connection_status == 0
        for: 5m
        labels:
          severity: warning
          priority: P2
          component: exchange
        annotations:
          summary: "交易所连接断开: {{ $labels.exchange }}"
          description: "交易所 {{ $labels.exchange }} 连接已断开超过5分钟"
          runbook_url: "https://docs.marketprism.com/runbooks/exchange-disconnected"
          action: "检查特定交易所API状态和配置"

      # NATS发布失败率高
      - alert: MarketPrismNATSPublishFailureHigh
        expr: |
          (
            sum(rate(marketprism_nats_publishes_total{status="failed"}[5m])) /
            sum(rate(marketprism_nats_publishes_total[5m]))
          ) * 100 > 10
        for: 10m
        labels:
          severity: warning
          priority: P2
          component: nats
        annotations:
          summary: "NATS发布失败率过高"
          description: "NATS发布失败率为 {{ $value | humanizePercentage }}，超过10%阈值"
          runbook_url: "https://docs.marketprism.com/runbooks/nats-publish-failure"
          action: "检查NATS服务状态和队列配置"

      # 消息处理速率异常下降
      - alert: MarketPrismMessageRateDropped
        expr: |
          (
            rate(marketprism_collector_messages_total[5m]) <
            0.5 * avg_over_time(rate(marketprism_collector_messages_total[5m])[1h:5m])
          )
        for: 10m
        labels:
          severity: warning
          priority: P2
          component: processing
        annotations:
          summary: "消息处理速率异常下降"
          description: "当前消息处理速率比1小时平均值低50%以上"
          runbook_url: "https://docs.marketprism.com/runbooks/message-rate-drop"
          action: "检查交易所数据流和系统负载"

  # === P3级告警 (一般 - 2小时内响应) ===
  - name: marketprism.info
    interval: 300s
    rules:
      # 内存使用过高
      - alert: MarketPrismHighMemoryUsage
        expr: marketprism_system_memory_usage_bytes / (1024^3) > 4.0
        for: 30m
        labels:
          severity: info
          priority: P3
          component: system
        annotations:
          summary: "内存使用过高"
          description: "系统内存使用为 {{ $value | humanize }}GB，超过4GB阈值"
          runbook_url: "https://docs.marketprism.com/runbooks/high-memory"
          action: "监控内存使用趋势，考虑优化或扩容"

      # CPU使用率过高
      - alert: MarketPrismHighCPUUsage
        expr: marketprism_system_cpu_usage_percent > 80
        for: 30m
        labels:
          severity: info
          priority: P3
          component: system
        annotations:
          summary: "CPU使用率过高"
          description: "系统CPU使用率为 {{ $value | humanizePercentage }}，超过80%阈值"
          runbook_url: "https://docs.marketprism.com/runbooks/high-cpu"
          action: "检查系统负载和进程状态"

      # 磁盘使用率过高
      - alert: MarketPrismHighDiskUsage
        expr: marketprism_system_disk_usage_percent > 85
        for: 30m
        labels:
          severity: info
          priority: P3
          component: system
        annotations:
          summary: "磁盘使用率过高"
          description: "系统磁盘使用率为 {{ $value | humanizePercentage }}，超过85%阈值"
          runbook_url: "https://docs.marketprism.com/runbooks/high-disk"
          action: "清理日志文件或扩展存储空间"

      # 频繁重连
      - alert: MarketPrismFrequentReconnects
        expr: rate(marketprism_websocket_reconnects_total[5m]) > 0.1
        for: 20m
        labels:
          severity: info
          priority: P3
          component: websocket
        annotations:
          summary: "WebSocket频繁重连: {{ $labels.exchange }}"
          description: "交易所 {{ $labels.exchange }} WebSocket重连频率为 {{ $value | humanize }}/秒"
          runbook_url: "https://docs.marketprism.com/runbooks/frequent-reconnects"
          action: "检查网络稳定性和交易所API限制"

      # 队列积压
      - alert: MarketPrismQueueBacklog
        expr: marketprism_queue_size > 1000
        for: 15m
        labels:
          severity: info
          priority: P3
          component: queue
        annotations:
          summary: "队列积压: {{ $labels.exchange }}"
          description: "交易所 {{ $labels.exchange }} 队列积压 {{ $value }} 条消息"
          runbook_url: "https://docs.marketprism.com/runbooks/queue-backlog"
          action: "检查处理性能和队列配置"

      # 数据新鲜度告警
      - alert: MarketPrismDataStale
        expr: |
          (time() - marketprism_collector_last_message_timestamp) > 300
        for: 10m
        labels:
          severity: info
          priority: P3
          component: data
        annotations:
          summary: "数据过期: {{ $labels.exchange }} {{ $labels.data_type }}"
          description: "{{ $labels.exchange }} 的 {{ $labels.data_type }} 数据已超过5分钟未更新"
          runbook_url: "https://docs.marketprism.com/runbooks/stale-data"
          action: "检查数据源和处理流程"

  # === 动态阈值告警 ===
  - name: marketprism.anomaly
    interval: 120s
    rules:
      # 消息处理速率异常
      - alert: MarketPrismAnomalousMessageRate
        expr: |
          abs(
            rate(marketprism_collector_messages_total[5m]) - 
            avg_over_time(rate(marketprism_collector_messages_total[5m])[1h:5m])
          ) > 
          2 * stddev_over_time(rate(marketprism_collector_messages_total[5m])[1h:5m])
        for: 10m
        labels:
          severity: warning
          priority: P2
          component: anomaly
        annotations:
          summary: "消息处理速率异常"
          description: "当前消息处理速率偏离1小时平均值超过2个标准差"
          runbook_url: "https://docs.marketprism.com/runbooks/anomalous-rate"
          action: "分析异常原因，检查数据源变化"

      # 错误率异常增长
      - alert: MarketPrismAnomalousErrorRate
        expr: |
          (
            rate(marketprism_collector_errors_total[5m]) - 
            avg_over_time(rate(marketprism_collector_errors_total[5m])[1h:5m])
          ) > 
          3 * stddev_over_time(rate(marketprism_collector_errors_total[5m])[1h:5m])
        for: 15m
        labels:
          severity: warning
          priority: P2
          component: anomaly
        annotations:
          summary: "错误率异常增长"
          description: "当前错误率比1小时平均值高出3个标准差以上"
          runbook_url: "https://docs.marketprism.com/runbooks/anomalous-errors"
          action: "调查错误原因，检查系统变更"