# MarketPrism 性能基线配置
# 定义各组件的性能基线和异常检测阈值

# 全局配置
global:
  baseline_collection_period: "7d"  # 基线数据收集周期
  anomaly_detection_window: "1h"    # 异常检测时间窗口
  confidence_level: 0.95             # 置信度
  update_frequency: "24h"            # 基线更新频率

# 服务性能基线
services:
  data-collector:
    # 响应时间基线 (毫秒)
    response_time:
      baseline_p50: 50      # 50分位数基线
      baseline_p95: 200     # 95分位数基线
      baseline_p99: 500     # 99分位数基线
      warning_threshold: 2.0  # 超过基线2倍告警
      critical_threshold: 5.0 # 超过基线5倍严重告警
    
    # 吞吐量基线 (请求/秒)
    throughput:
      baseline_avg: 100     # 平均吞吐量基线
      baseline_peak: 500    # 峰值吞吐量基线
      warning_threshold: 0.5  # 低于基线50%告警
      critical_threshold: 0.2 # 低于基线20%严重告警
    
    # 错误率基线 (%)
    error_rate:
      baseline_avg: 0.1     # 平均错误率基线
      baseline_max: 1.0     # 最大错误率基线
      warning_threshold: 5.0  # 超过基线5倍告警
      critical_threshold: 10.0 # 超过基线10倍严重告警
    
    # CPU使用率基线 (%)
    cpu_usage:
      baseline_avg: 30      # 平均CPU使用率基线
      baseline_peak: 70     # 峰值CPU使用率基线
      warning_threshold: 80   # 超过80%告警
      critical_threshold: 90  # 超过90%严重告警
    
    # 内存使用率基线 (%)
    memory_usage:
      baseline_avg: 40      # 平均内存使用率基线
      baseline_peak: 60     # 峰值内存使用率基线
      warning_threshold: 80   # 超过80%告警
      critical_threshold: 90  # 超过90%严重告警

  api-gateway:
    response_time:
      baseline_p50: 30
      baseline_p95: 100
      baseline_p99: 300
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    throughput:
      baseline_avg: 200
      baseline_peak: 1000
      warning_threshold: 0.5
      critical_threshold: 0.2
    
    error_rate:
      baseline_avg: 0.05
      baseline_max: 0.5
      warning_threshold: 5.0
      critical_threshold: 10.0

  monitoring-alerting:
    response_time:
      baseline_p50: 20
      baseline_p95: 80
      baseline_p99: 200
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    alert_processing_time:
      baseline_avg: 100     # 告警处理时间基线 (毫秒)
      baseline_max: 1000
      warning_threshold: 2.0
      critical_threshold: 5.0

# 交易所连接性能基线
exchanges:
  binance:
    # 连接延迟基线 (毫秒)
    connection_latency:
      baseline_avg: 50
      baseline_p95: 150
      baseline_p99: 300
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    # WebSocket消息延迟基线 (毫秒)
    websocket_latency:
      baseline_avg: 20
      baseline_p95: 100
      baseline_p99: 200
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    # 数据收集成功率基线 (%)
    data_collection_success_rate:
      baseline_avg: 99.5
      baseline_min: 98.0
      warning_threshold: 0.95  # 低于基线95%告警
      critical_threshold: 0.90 # 低于基线90%严重告警
    
    # API限流使用率基线 (%)
    rate_limit_usage:
      baseline_avg: 30
      baseline_peak: 70
      warning_threshold: 80
      critical_threshold: 90

  okx:
    connection_latency:
      baseline_avg: 60
      baseline_p95: 180
      baseline_p99: 350
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    websocket_latency:
      baseline_avg: 25
      baseline_p95: 120
      baseline_p99: 250
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    data_collection_success_rate:
      baseline_avg: 99.0
      baseline_min: 97.0
      warning_threshold: 0.95
      critical_threshold: 0.90

  deribit:
    connection_latency:
      baseline_avg: 80
      baseline_p95: 200
      baseline_p99: 400
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    websocket_latency:
      baseline_avg: 30
      baseline_p95: 150
      baseline_p99: 300
      warning_threshold: 2.0
      critical_threshold: 5.0

# 基础设施性能基线
infrastructure:
  nats:
    # 消息处理延迟基线 (毫秒)
    message_latency:
      baseline_p50: 5
      baseline_p95: 20
      baseline_p99: 50
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    # 消息吞吐量基线 (消息/秒)
    message_throughput:
      baseline_avg: 1000
      baseline_peak: 5000
      warning_threshold: 0.5
      critical_threshold: 0.2
    
    # 队列积压基线 (消息数)
    queue_backlog:
      baseline_avg: 100
      baseline_max: 1000
      warning_threshold: 5.0
      critical_threshold: 10.0

  clickhouse:
    # 查询响应时间基线 (毫秒)
    query_latency:
      baseline_p50: 100
      baseline_p95: 500
      baseline_p99: 2000
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    # 插入性能基线 (行/秒)
    insert_throughput:
      baseline_avg: 10000
      baseline_peak: 50000
      warning_threshold: 0.5
      critical_threshold: 0.2
    
    # 磁盘使用率基线 (%)
    disk_usage:
      baseline_avg: 50
      baseline_max: 80
      warning_threshold: 85
      critical_threshold: 95

  redis:
    # 命令响应时间基线 (毫秒)
    command_latency:
      baseline_p50: 1
      baseline_p95: 5
      baseline_p99: 10
      warning_threshold: 2.0
      critical_threshold: 5.0
    
    # 内存使用率基线 (%)
    memory_usage:
      baseline_avg: 30
      baseline_max: 70
      warning_threshold: 80
      critical_threshold: 90

# 异常检测算法配置
anomaly_detection:
  algorithms:
    # 统计异常检测
    statistical:
      enabled: true
      z_score_threshold: 3.0    # Z-score阈值
      iqr_multiplier: 1.5       # IQR异常值倍数
      
    # 时间序列异常检测
    time_series:
      enabled: true
      seasonal_period: "24h"    # 季节性周期
      trend_window: "7d"        # 趋势分析窗口
      
    # 机器学习异常检测
    ml_based:
      enabled: false            # 暂时禁用，需要更多历史数据
      model_type: "isolation_forest"
      training_period: "30d"

# 基线更新策略
baseline_update:
  # 自动更新配置
  auto_update:
    enabled: true
    update_schedule: "0 2 * * *"  # 每天凌晨2点更新
    min_data_points: 1000         # 最少数据点要求
    
  # 手动更新触发条件
  manual_triggers:
    - "deployment_completed"      # 部署完成后
    - "configuration_changed"     # 配置变更后
    - "performance_degradation"   # 性能下降后
    
  # 基线验证
  validation:
    enabled: true
    validation_period: "3d"      # 验证期间
    rollback_threshold: 0.1      # 回滚阈值

# 告警集成
alerting:
  # 基线偏离告警
  baseline_deviation:
    enabled: true
    severity_mapping:
      warning: "baseline_warning_threshold"
      critical: "baseline_critical_threshold"
  
  # 异常检测告警
  anomaly_alerts:
    enabled: true
    min_anomaly_score: 0.8      # 最小异常分数
    consecutive_anomalies: 3     # 连续异常次数阈值
